/*
 * Copyright 2025 Cisco Systems, Inc. and its affiliates
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { VarsType } from "@/types/vars";
import {
  greenPalette,
  greyPalette,
  lightOrangePalette,
  redPalette,
  lightBluePalette,
  purplePalette,
  orangePalette,
  yellowPalette,
  nightPalette,
  sunsetPalette,
  lavenderPalette,
  limePalette,
  pinkPalette,
  tealPalette,
} from "../color-palette";
import {
  glassLightAccentPalette,
  glassLightHighlightPalette,
  glassLightSurfacePalette,
  glassLightBackdropPalette,
  glassLightBorderPalette,
  glassLightTextPrimary,
  glassLightTextSecondary,
  glassLightTextTertiary,
  glassLightTextDisabled,
} from "./glass-light-color-palette";

// Glass Light Theme Variables
// Optimized for light mode glassmorphism with frosted white surfaces

export const glassLightVars: VarsType = {
  // Brand Colors
  brandOrange: lightOrangePalette[600],
  brandOrangeDark: lightOrangePalette[800],
  brandBlue: glassLightAccentPalette[600],
  brandMidnightBlue: glassLightBackdropPalette[900],
  agentcyYellow: lightOrangePalette[500],
  agentcyBlue: glassLightAccentPalette[500],
  agentcyDarkBlue: glassLightBackdropPalette[900],

  // Base Text - Dark on light for readability
  baseTextStrong: glassLightTextPrimary,
  baseTextDefault: glassLightTextSecondary,
  baseTextMedium: glassLightTextTertiary,
  baseTextWeak: glassLightTextDisabled,
  baseTextInverse: "rgba(255, 255, 255, 0.95)",
  baseTextDisabled: glassLightTextDisabled,

  // Base Background - Translucent white surfaces
  baseBackgroundStrong: glassLightSurfacePalette[800],
  baseBackgroundMedium: glassLightSurfacePalette[500],
  baseBackgroundWeak: glassLightSurfacePalette[300],
  baseBackgroundHover: glassLightSurfacePalette[600],

  // Base Border - Subtle dark borders on light
  baseBorderDefault: glassLightBorderPalette[400],
  baseBorderStrong: glassLightBorderPalette[700],
  baseBorderMedium: glassLightBorderPalette[300],
  baseBorderWeak: glassLightBorderPalette[100],

  // Brand Icon - Cyan accent
  brandIconPrimaryDefault: glassLightAccentPalette[600],
  brandIconPrimaryWeak: glassLightAccentPalette[300],
  brandIconPrimaryMedium: glassLightAccentPalette[500],
  brandIconPrimaryStrong: glassLightAccentPalette[800],
  brandIconSecondaryDefault: glassLightHighlightPalette[600],
  brandIconSecondaryWeak: glassLightHighlightPalette[300],
  brandIconSecondaryMedium: glassLightHighlightPalette[500],
  brandIconTertiaryDefault: lightOrangePalette[600],
  brandIconTertiaryWeak: lightOrangePalette[300],
  brandIconTertiaryMedium: lightOrangePalette[500],

  // Brand Background
  brandBackgroundPrimaryDefault: glassLightAccentPalette[500],
  brandBackgroundPrimaryWeak: glassLightAccentPalette.alpha10,
  brandBackgroundPrimaryMedium: glassLightAccentPalette.alpha20,
  brandBackgroundSecondaryDefault: glassLightHighlightPalette[500],
  brandLogoPrimary: glassLightAccentPalette[600],
  brandTextPrimary: glassLightAccentPalette[700],
  brandTextSecondary: glassLightTextPrimary,

  // Control - Glass-style controls
  controlBackgroundDefault: glassLightSurfacePalette[600],
  controlBackgroundDisabled: glassLightSurfacePalette[300],
  controlBackgroundWeak: glassLightSurfacePalette[400],
  controlBackgroundMedium: glassLightSurfacePalette[700],
  controlBorderDefault: glassLightBorderPalette[400],
  controlBorderStrong: glassLightBorderPalette[600],
  controlBorderMedium: glassLightBorderPalette[300],
  controlBorderWeak: glassLightBorderPalette[200],
  controlBorderHover: glassLightAccentPalette[500],
  controlBorderActive: glassLightAccentPalette[600],
  controlBorderNegative: redPalette[500],
  controlBorderDisabled: glassLightBorderPalette[100],
  controlIconDefault: glassLightTextSecondary,
  controlIconStrong: glassLightTextPrimary,
  controlIconMedium: glassLightTextTertiary,
  controlIconWeak: glassLightTextDisabled,
  controlIconHover: glassLightAccentPalette[600],
  controlIconActive: glassLightAccentPalette[700],
  controlIconDisabled: glassLightTextDisabled,

  // Interactive Primary - Cyan accent
  interactivePrimaryDefaultDefault: glassLightAccentPalette[500],
  interactivePrimaryDefaultHover: glassLightAccentPalette[400],
  interactivePrimaryDefaultActive: glassLightAccentPalette[600],
  interactivePrimaryDefaultDisabled: glassLightAccentPalette.alpha40,
  interactivePrimaryWeakDefault: glassLightAccentPalette.alpha10,
  interactivePrimaryWeakHover: glassLightAccentPalette.alpha20,
  interactivePrimaryWeakActive: glassLightAccentPalette.alpha40,
  interactivePrimaryWeakDisabled: "rgba(0, 188, 212, 0.05)",

  // Interactive Secondary - Purple highlight
  interactiveSecondaryDefaultDefault: glassLightHighlightPalette[500],
  interactiveSecondaryDefaultHover: glassLightHighlightPalette[400],
  interactiveSecondaryDefaultActive: glassLightHighlightPalette[600],
  interactiveSecondaryDefaultDisabled: glassLightHighlightPalette.alpha40,
  interactiveSecondaryWeakDefault: glassLightSurfacePalette[500],
  interactiveSecondaryWeakHover: glassLightSurfacePalette[600],
  interactiveSecondaryWeakActive: glassLightSurfacePalette[700],
  interactiveSecondaryWeakDisabled: glassLightSurfacePalette[300],

  // Interactive Inverse
  interactiveInverseBackgroundDefault: "rgba(0, 0, 0, 0.85)",
  interactiveInverseBackgroundHover: "rgba(0, 0, 0, 0.75)",
  interactiveInverseBackgroundActive: "rgba(0, 0, 0, 0.90)",
  interactiveInverseBackgroundDisabled: "rgba(0, 0, 0, 0.30)",
  interactiveInverseTextDefault: "rgba(255, 255, 255, 0.95)",
  interactiveInverseTextHover: "rgba(255, 255, 255, 0.85)",
  interactiveInverseTextActive: "rgba(255, 255, 255, 0.90)",
  interactiveInverseTextDisabled: "rgba(255, 255, 255, 0.40)",

  // Interactive Text In
  interactiveTextInDefault: "rgba(255, 255, 255, 0.95)",
  interactiveTextInHover: "rgba(255, 255, 255, 0.90)",
  interactiveTextInActive: "rgba(255, 255, 255, 0.95)",
  interactiveTextInDisabled: "rgba(255, 255, 255, 0.50)",

  // Interactive Tertiary
  interactiveTertiaryDefault: lightOrangePalette[600],
  interactiveTertiaryHover: lightOrangePalette[500],
  interactiveTertiaryActive: lightOrangePalette[700],
  interactiveTertiaryDisabled: lightOrangePalette["alpha40"],

  // Success
  successBackgroundDefault: greenPalette[500],
  successBackgroundDisabled: greenPalette[40],
  successBackgroundHover: greenPalette[400],
  successBackgroundActive: greenPalette[600],
  successBackgroundWeak: "rgba(0, 185, 141, 0.12)",
  successIconActive: greenPalette[700],
  successIconDisabled: greenPalette[40],
  successIconHover: greenPalette[500],
  successIconDefault: greenPalette[600],
  successTextActive: greenPalette[700],
  successTextHover: greenPalette[600],
  successTextDefault: greenPalette[700],
  successTextInDisabled: greenPalette[10],
  successTextInDefault: greenPalette[50],
  successBorderDisabled: greenPalette[40],
  successBorderActive: greenPalette[700],
  successBorderHover: greenPalette[500],
  successBorderDefault: greenPalette[600],
  successBorderWeak: "rgba(0, 185, 141, 0.25)",
  successIconInDisabled: greenPalette[10],
  successIconInActive: greenPalette[200],
  successIconInHover: greenPalette[100],
  successIconInDefault: greenPalette[50],

  // Negative
  negativeBackgroundHover: redPalette[400],
  negativeBackgroundActive: redPalette[600],
  negativeBackgroundDisabled: redPalette["alpha40"],
  negativeBackgroundDefault: redPalette[500],
  negativeBackgroundWeak: "rgba(198, 41, 83, 0.12)",
  negativeTextDefault: redPalette[700],
  negativeTextHover: redPalette[600],
  negativeTextActive: redPalette[800],
  negativeBorderActive: redPalette[700],
  negativeBorderHover: redPalette[500],
  negativeBorderDisabled: redPalette["alpha40"],
  negativeBorderDefault: redPalette[600],
  negativeBorderWeak: "rgba(198, 41, 83, 0.25)",
  negativeIconDisabled: redPalette["alpha40"],
  negativeIconActive: redPalette[700],
  negativeIconHover: redPalette[500],
  negativeIconDefault: redPalette[600],
  negativeTextInDefault: redPalette[50],
  negativeTextInDisabled: redPalette["alpha10"],
  negativeIconInDefault: redPalette[50],
  negativeIconInHover: redPalette[100],
  negativeIconInActive: redPalette[200],
  negativeIconInDisabled: redPalette["alpha10"],

  // Excellent
  excellentBackgroundDefault: lightBluePalette[600],
  excellentBackgroundWeak: "rgba(31, 210, 255, 0.12)",
  excellentBackgroundDisabled: lightBluePalette["alpha40"],
  excellentBackgroundHover: lightBluePalette[500],
  excellentBackgroundActive: lightBluePalette[700],
  excellentTextDefault: lightBluePalette[800],
  excellentTextHover: lightBluePalette[700],
  excellentTextActive: lightBluePalette[900],
  excellentTextInDefault: lightBluePalette[50],
  excellentTextInDisabled: lightBluePalette["alpha10"],
  excellentBorderDefault: lightBluePalette[600],
  excellentBorderHover: lightBluePalette[500],
  excellentBorderActive: lightBluePalette[700],
  excellentBorderDisabled: lightBluePalette["alpha40"],
  excellentBorderWeak: "rgba(31, 210, 255, 0.25)",
  excellentIconDefault: lightBluePalette[600],
  excellentIconHover: lightBluePalette[500],
  excellentIconActive: lightBluePalette[700],
  excellentIconDisabled: lightBluePalette["alpha40"],
  excellentIconInDefault: lightBluePalette[50],
  excellentIconInHover: lightBluePalette[100],
  excellentIconInActive: lightBluePalette[200],
  excellentIconInDisabled: lightBluePalette["alpha10"],

  // Neutral
  neutralBackgroundDefault: glassLightAccentPalette[600],
  neutralBackgroundWeak: glassLightAccentPalette.alpha10,
  neutralBackgroundDisabled: glassLightAccentPalette.alpha40,
  neutralBackgroundHover: glassLightAccentPalette[500],
  neutralBackgroundActive: glassLightAccentPalette[700],
  neutralTextDefault: glassLightAccentPalette[800],
  neutralTextHover: glassLightAccentPalette[700],
  neutralTextActive: glassLightAccentPalette[900],
  neutralTextInDefault: glassLightAccentPalette[50],
  neutralTextInDisabled: glassLightAccentPalette.alpha10,
  neutralBorderDefault: glassLightAccentPalette[600],
  neutralBorderHover: glassLightAccentPalette[500],
  neutralBorderActive: glassLightAccentPalette[700],
  neutralBorderDisabled: glassLightAccentPalette.alpha40,
  neutralBorderWeak: glassLightAccentPalette.alpha20,
  neutralIconDefault: glassLightAccentPalette[600],
  neutralIconHover: glassLightAccentPalette[500],
  neutralIconActive: glassLightAccentPalette[700],
  neutralIconDisabled: glassLightAccentPalette.alpha40,
  neutralIconInDefault: glassLightAccentPalette[50],
  neutralIconInHover: glassLightAccentPalette[100],
  neutralIconInActive: glassLightAccentPalette[200],
  neutralIconInDisabled: glassLightAccentPalette.alpha10,

  // Info
  infoBackgroundDefault: glassLightHighlightPalette[600],
  infoBackgroundWeak: glassLightHighlightPalette.alpha10,
  infoBackgroundDisabled: glassLightHighlightPalette.alpha40,
  infoBackgroundHover: glassLightHighlightPalette[500],
  infoBackgroundActive: glassLightHighlightPalette[700],
  infoTextDefault: glassLightHighlightPalette[800],
  infoTextHover: glassLightHighlightPalette[700],
  infoTextActive: glassLightHighlightPalette[900],
  infoTextInDefault: glassLightHighlightPalette[50],
  infoTextInDisabled: glassLightHighlightPalette.alpha10,
  infoBorderDefault: glassLightHighlightPalette[600],
  infoBorderHover: glassLightHighlightPalette[500],
  infoBorderActive: glassLightHighlightPalette[700],
  infoBorderDisabled: glassLightHighlightPalette.alpha40,
  infoBorderWeak: glassLightHighlightPalette.alpha20,
  infoIconDefault: glassLightHighlightPalette[600],
  infoIconHover: glassLightHighlightPalette[500],
  infoIconActive: glassLightHighlightPalette[700],
  infoIconDisabled: glassLightHighlightPalette.alpha40,
  infoIconInDefault: glassLightHighlightPalette[50],
  infoIconInHover: glassLightHighlightPalette[100],
  infoIconInActive: glassLightHighlightPalette[200],
  infoIconInDisabled: glassLightHighlightPalette.alpha10,

  // Inactive
  inactiveBackgroundDefault: greyPalette[400],
  inactiveBackgroundWeak: "rgba(60, 69, 81, 0.08)",
  inactiveBackgroundDisabled: greyPalette["alpha40"],
  inactiveBackgroundHover: greyPalette[300],
  inactiveBackgroundActive: greyPalette[500],
  inactiveTextDefault: greyPalette[600],
  inactiveTextHover: greyPalette[500],
  inactiveTextActive: greyPalette[700],
  inactiveTextInDefault: greyPalette[50],
  inactiveTextInDisabled: greyPalette["alpha40"],
  inactiveBorderDefault: greyPalette[400],
  inactiveBorderHover: greyPalette[300],
  inactiveBorderActive: greyPalette[500],
  inactiveBorderDisabled: greyPalette["alpha40"],
  inactiveBorderWeak: "rgba(60, 69, 81, 0.15)",
  inactiveIconDefault: greyPalette[500],
  inactiveIconHover: greyPalette[400],
  inactiveIconActive: greyPalette[600],
  inactiveIconDisabled: greyPalette["alpha40"],
  inactiveIconInDefault: greyPalette[0],
  inactiveIconInHover: greyPalette[50],
  inactiveIconInActive: greyPalette[100],
  inactiveIconInDisabled: greyPalette["alpha10"],

  // Warning
  warningBackgroundDefault: lightOrangePalette[500],
  warningBackgroundWeak: "rgba(251, 175, 69, 0.12)",
  warningBackgroundHover: lightOrangePalette[400],
  warningBackgroundActive: lightOrangePalette[600],
  warningBackgroundDisabled: lightOrangePalette["alpha40"],
  warningTextDefault: lightOrangePalette[800],
  warningTextHover: lightOrangePalette[700],
  warningTextActive: lightOrangePalette[900],
  warningTextInDefault: lightOrangePalette[900],
  warningTextInDisabled: lightOrangePalette["alpha10"],
  warningBorderDefault: lightOrangePalette[600],
  warningBorderHover: lightOrangePalette[500],
  warningBorderActive: lightOrangePalette[700],
  warningBorderDisabled: lightOrangePalette["alpha40"],
  warningBorderWeak: "rgba(251, 175, 69, 0.25)",
  warningIconDefault: lightOrangePalette[700],
  warningIconHover: lightOrangePalette[600],
  warningIconActive: lightOrangePalette[800],
  warningIconDisabled: lightOrangePalette["alpha40"],
  warningIconInDefault: lightOrangePalette[900],
  warningIconInHover: lightOrangePalette[800],
  warningIconInActive: lightOrangePalette[700],
  warningIconInDisabled: lightOrangePalette["alpha10"],

  // Severe Warning
  severeWarningBackgroundDefault: orangePalette[500],
  severeWarningBackgroundWeak: "rgba(242, 100, 61, 0.12)",
  severeWarningBackgroundHover: orangePalette[400],
  severeWarningBackgroundActive: orangePalette[600],
  severeWarningBackgroundDisabled: orangePalette["alpha40"],
  severeWarningTextDefault: orangePalette[800],
  severeWarningTextHover: orangePalette[700],
  severeWarningTextActive: orangePalette[900],
  severeWarningTextInDefault: orangePalette[50],
  severeWarningTextInDisabled: orangePalette["alpha10"],
  severeWarningBorderDefault: orangePalette[600],
  severeWarningBorderHover: orangePalette[500],
  severeWarningBorderActive: orangePalette[700],
  severeWarningBorderDisabled: orangePalette["alpha40"],
  severeWarningBorderWeak: "rgba(242, 100, 61, 0.25)",
  severeWarningIconDefault: orangePalette[700],
  severeWarningIconHover: orangePalette[600],
  severeWarningIconActive: orangePalette[800],
  severeWarningIconDisabled: orangePalette["alpha40"],
  severeWarningIconInDefault: orangePalette[50],
  severeWarningIconInHover: orangePalette[100],
  severeWarningIconInActive: orangePalette[200],
  severeWarningIconInDisabled: orangePalette["alpha10"],

  // Moderate
  moderateBackgroundDefault: yellowPalette[500],
  moderateBackgroundWeak: "rgba(255, 230, 89, 0.15)",
  moderateBackgroundHover: yellowPalette[400],
  moderateBackgroundActive: yellowPalette[600],
  moderateBackgroundDisabled: yellowPalette["alpha40"],
  moderateTextDefault: yellowPalette[900],
  moderateTextHover: yellowPalette[800],
  moderateTextActive: yellowPalette[900],
  moderateTextInDefault: yellowPalette[900],
  moderateTextInDisabled: yellowPalette["alpha10"],
  moderateBorderDefault: yellowPalette[600],
  moderateBorderHover: yellowPalette[500],
  moderateBorderActive: yellowPalette[700],
  moderateBorderDisabled: yellowPalette["alpha40"],
  moderateBorderWeak: "rgba(255, 230, 89, 0.35)",
  moderateIconDefault: yellowPalette[800],
  moderateIconHover: yellowPalette[700],
  moderateIconActive: yellowPalette[900],
  moderateIconDisabled: yellowPalette["alpha40"],
  moderateIconInDefault: yellowPalette[900],
  moderateIconInHover: yellowPalette[800],
  moderateIconInActive: yellowPalette[700],
  moderateIconInDisabled: yellowPalette["alpha10"],

  // Accent Colors
  accentADefault: lavenderPalette[600],
  accentAWeak: "rgba(92, 109, 221, 0.12)",
  accentBDefault: sunsetPalette[500],
  accentBWeak: "rgba(184, 66, 140, 0.12)",
  accentCDefault: sunsetPalette[300],
  accentCWeak: "rgba(233, 106, 141, 0.12)",
  accentDDefault: purplePalette[600],
  accentDWeak: "rgba(156, 78, 234, 0.12)",
  accentEDefault: limePalette[600],
  accentEWeak: "rgba(125, 161, 27, 0.12)",
  accentFDefault: orangePalette[600],
  accentFWeak: "rgba(240, 92, 55, 0.12)",
  accentGDefault: nightPalette[400],
  accentGWeak: "rgba(53, 119, 174, 0.12)",
  accentHDefault: glassLightAccentPalette[600],
  accentHWeak: "rgba(0, 165, 187, 0.12)",
  accentIDefault: pinkPalette[600],
  accentIWeak: "rgba(194, 48, 111, 0.12)",
  accentJDefault: tealPalette[600],
  accentJWeak: "rgba(2, 142, 153, 0.12)",
};
