/*
 * Copyright 2025 Cisco Systems, Inc. and its affiliates
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { VarsType } from "@/types/vars";
import {
  greenPalette,
  greyPalette,
  lightOrangePalette,
  redPalette,
  lightBluePalette,
  purplePalette,
  orangePalette,
  yellowPalette,
  nightPalette,
  sunsetPalette,
  lavenderPalette,
  limePalette,
  pinkPalette,
  tealPalette,
} from "../color-palette";
import {
  glassAccentPalette,
  glassHighlightPalette,
  glassSurfacePalette,
  glassBackdropPalette,
  glassBorderPalette,
  glassTextPrimary,
  glassTextSecondary,
  glassTextTertiary,
  glassTextDisabled,
} from "./glass-color-palette";

// Glass Theme Variables
// Optimized for glassmorphism UI with translucent surfaces and frosted effects

export const glassVars: VarsType = {
  // Brand Colors - Using cyan accent for glass theme
  brandOrange: lightOrangePalette[500],
  brandOrangeDark: lightOrangePalette[900],
  brandBlue: glassAccentPalette[500],
  brandMidnightBlue: glassBackdropPalette[500],
  agentcyYellow: lightOrangePalette[500],
  agentcyBlue: glassAccentPalette[500],
  agentcyDarkBlue: glassBackdropPalette[900],

  // Base Text - Glass-optimized with high contrast on translucent backgrounds
  baseTextStrong: glassTextPrimary,
  baseTextDefault: glassTextSecondary,
  baseTextMedium: glassTextTertiary,
  baseTextWeak: glassTextDisabled,
  baseTextInverse: glassBackdropPalette[900],
  baseTextDisabled: glassTextDisabled,

  // Base Background - Translucent glass surfaces
  baseBackgroundStrong: glassBackdropPalette[900],
  baseBackgroundMedium: glassSurfacePalette[200],
  baseBackgroundWeak: glassSurfacePalette[100],
  baseBackgroundHover: glassSurfacePalette[300],

  // Base Border - Subtle glass edges
  baseBorderDefault: glassBorderPalette[400],
  baseBorderStrong: glassBorderPalette[700],
  baseBorderMedium: glassBorderPalette[300],
  baseBorderWeak: glassBorderPalette[100],

  // Brand Icon - Cyan accent glow
  brandIconPrimaryDefault: glassAccentPalette[500],
  brandIconPrimaryWeak: glassAccentPalette[200],
  brandIconPrimaryMedium: glassAccentPalette[400],
  brandIconPrimaryStrong: glassAccentPalette[700],
  brandIconSecondaryDefault: glassHighlightPalette[400],
  brandIconSecondaryWeak: glassHighlightPalette[200],
  brandIconSecondaryMedium: glassHighlightPalette[500],
  brandIconTertiaryDefault: lightOrangePalette[500],
  brandIconTertiaryWeak: lightOrangePalette[200],
  brandIconTertiaryMedium: lightOrangePalette[400],

  // Brand Background - Glass with accent tints
  brandBackgroundPrimaryDefault: glassAccentPalette[500],
  brandBackgroundPrimaryWeak: glassAccentPalette.alpha10,
  brandBackgroundPrimaryMedium: glassAccentPalette.alpha20,
  brandBackgroundSecondaryDefault: glassHighlightPalette[500],
  brandLogoPrimary: glassAccentPalette[400],
  brandTextPrimary: glassAccentPalette[400],
  brandTextSecondary: glassTextPrimary,

  // Control - Glass-style controls with frosted appearance
  controlBackgroundDefault: glassSurfacePalette[100],
  controlBackgroundDisabled: glassSurfacePalette[50],
  controlBackgroundWeak: glassSurfacePalette[50],
  controlBackgroundMedium: glassSurfacePalette[300],
  controlBorderDefault: glassBorderPalette[400],
  controlBorderStrong: glassBorderPalette[600],
  controlBorderMedium: glassBorderPalette[300],
  controlBorderWeak: glassBorderPalette[200],
  controlBorderHover: glassAccentPalette[500],
  controlBorderActive: glassAccentPalette[600],
  controlBorderNegative: redPalette[500],
  controlBorderDisabled: glassBorderPalette[100],
  controlIconDefault: glassTextSecondary,
  controlIconStrong: glassTextPrimary,
  controlIconMedium: glassTextTertiary,
  controlIconWeak: glassTextDisabled,
  controlIconHover: glassAccentPalette[400],
  controlIconActive: glassAccentPalette[500],
  controlIconDisabled: glassTextDisabled,

  // Interactive Primary - Cyan accent for primary actions
  interactivePrimaryDefaultDefault: glassAccentPalette[500],
  interactivePrimaryDefaultHover: glassAccentPalette[400],
  interactivePrimaryDefaultActive: glassAccentPalette[600],
  interactivePrimaryDefaultDisabled: glassAccentPalette.alpha40,
  interactivePrimaryWeakDefault: glassAccentPalette.alpha10,
  interactivePrimaryWeakHover: glassAccentPalette.alpha20,
  interactivePrimaryWeakActive: glassAccentPalette.alpha40,
  interactivePrimaryWeakDisabled: "rgba(0, 212, 255, 0.05)",

  // Interactive Secondary - Purple highlight for secondary actions
  interactiveSecondaryDefaultDefault: glassHighlightPalette[500],
  interactiveSecondaryDefaultHover: glassHighlightPalette[400],
  interactiveSecondaryDefaultActive: glassHighlightPalette[600],
  interactiveSecondaryDefaultDisabled: glassHighlightPalette.alpha40,
  interactiveSecondaryWeakDefault: glassSurfacePalette[200],
  interactiveSecondaryWeakHover: glassSurfacePalette[300],
  interactiveSecondaryWeakActive: glassSurfacePalette[400],
  interactiveSecondaryWeakDisabled: glassSurfacePalette[100],

  // Interactive Inverse - Light on dark glass
  interactiveInverseBackgroundDefault: "rgba(255, 255, 255, 0.90)",
  interactiveInverseBackgroundHover: "rgba(255, 255, 255, 0.95)",
  interactiveInverseBackgroundActive: "rgba(255, 255, 255, 0.85)",
  interactiveInverseBackgroundDisabled: "rgba(255, 255, 255, 0.40)",
  interactiveInverseTextDefault: glassBackdropPalette[900],
  interactiveInverseTextHover: glassBackdropPalette[700],
  interactiveInverseTextActive: glassBackdropPalette[800],
  interactiveInverseTextDisabled: "rgba(0, 0, 0, 0.30)",

  // Interactive Text In - Text on interactive surfaces
  interactiveTextInDefault: glassTextPrimary,
  interactiveTextInHover: glassTextPrimary,
  interactiveTextInActive: glassTextPrimary,
  interactiveTextInDisabled: glassTextDisabled,

  // Interactive Tertiary - Orange accent
  interactiveTertiaryDefault: lightOrangePalette[500],
  interactiveTertiaryHover: lightOrangePalette[400],
  interactiveTertiaryActive: lightOrangePalette[600],
  interactiveTertiaryDisabled: lightOrangePalette["alpha40"],

  // Success - Green with glass overlay feel
  successBackgroundDefault: greenPalette[500],
  successBackgroundDisabled: greenPalette[40],
  successBackgroundHover: greenPalette[400],
  successBackgroundActive: greenPalette[600],
  successBackgroundWeak: "rgba(0, 185, 141, 0.10)",
  successIconActive: greenPalette[600],
  successIconDisabled: greenPalette[40],
  successIconHover: greenPalette[400],
  successIconDefault: greenPalette[500],
  successTextActive: greenPalette[300],
  successTextHover: greenPalette[200],
  successTextDefault: greenPalette[300],
  successTextInDisabled: greenPalette[10],
  successTextInDefault: greenPalette[50],
  successBorderDisabled: greenPalette[40],
  successBorderActive: greenPalette[600],
  successBorderHover: greenPalette[400],
  successBorderDefault: greenPalette[500],
  successBorderWeak: "rgba(0, 185, 141, 0.30)",
  successIconInDisabled: greenPalette[10],
  successIconInActive: greenPalette[200],
  successIconInHover: greenPalette[100],
  successIconInDefault: greenPalette[50],

  // Negative - Red with glass styling
  negativeBackgroundHover: redPalette[400],
  negativeBackgroundActive: redPalette[600],
  negativeBackgroundDisabled: redPalette["alpha40"],
  negativeBackgroundDefault: redPalette[500],
  negativeBackgroundWeak: "rgba(198, 41, 83, 0.10)",
  negativeTextDefault: redPalette[300],
  negativeTextHover: redPalette[200],
  negativeTextActive: redPalette[400],
  negativeBorderActive: redPalette[600],
  negativeBorderHover: redPalette[400],
  negativeBorderDisabled: redPalette["alpha40"],
  negativeBorderDefault: redPalette[500],
  negativeBorderWeak: "rgba(198, 41, 83, 0.30)",
  negativeIconDisabled: redPalette["alpha40"],
  negativeIconActive: redPalette[600],
  negativeIconHover: redPalette[400],
  negativeIconDefault: redPalette[500],
  negativeTextInDefault: redPalette[50],
  negativeTextInDisabled: redPalette["alpha10"],
  negativeIconInDefault: redPalette[50],
  negativeIconInHover: redPalette[100],
  negativeIconInActive: redPalette[200],
  negativeIconInDisabled: redPalette["alpha10"],

  // Excellent - Light blue with glass effect
  excellentBackgroundDefault: lightBluePalette[600],
  excellentBackgroundWeak: "rgba(31, 210, 255, 0.10)",
  excellentBackgroundDisabled: lightBluePalette["alpha40"],
  excellentBackgroundHover: lightBluePalette[500],
  excellentBackgroundActive: lightBluePalette[700],
  excellentTextDefault: lightBluePalette[200],
  excellentTextHover: lightBluePalette[100],
  excellentTextActive: lightBluePalette[300],
  excellentTextInDefault: lightBluePalette[50],
  excellentTextInDisabled: lightBluePalette["alpha10"],
  excellentBorderDefault: lightBluePalette[600],
  excellentBorderHover: lightBluePalette[500],
  excellentBorderActive: lightBluePalette[700],
  excellentBorderDisabled: lightBluePalette["alpha40"],
  excellentBorderWeak: "rgba(31, 210, 255, 0.30)",
  excellentIconDefault: lightBluePalette[500],
  excellentIconHover: lightBluePalette[400],
  excellentIconActive: lightBluePalette[600],
  excellentIconDisabled: lightBluePalette["alpha40"],
  excellentIconInDefault: lightBluePalette[50],
  excellentIconInHover: lightBluePalette[100],
  excellentIconInActive: lightBluePalette[200],
  excellentIconInDisabled: lightBluePalette["alpha10"],

  // Neutral - Blue with glass styling
  neutralBackgroundDefault: glassAccentPalette[600],
  neutralBackgroundWeak: glassAccentPalette.alpha10,
  neutralBackgroundDisabled: glassAccentPalette.alpha40,
  neutralBackgroundHover: glassAccentPalette[500],
  neutralBackgroundActive: glassAccentPalette[700],
  neutralTextDefault: glassAccentPalette[200],
  neutralTextHover: glassAccentPalette[100],
  neutralTextActive: glassAccentPalette[300],
  neutralTextInDefault: glassAccentPalette[50],
  neutralTextInDisabled: glassAccentPalette.alpha10,
  neutralBorderDefault: glassAccentPalette[600],
  neutralBorderHover: glassAccentPalette[500],
  neutralBorderActive: glassAccentPalette[700],
  neutralBorderDisabled: glassAccentPalette.alpha40,
  neutralBorderWeak: glassAccentPalette.alpha20,
  neutralIconDefault: glassAccentPalette[500],
  neutralIconHover: glassAccentPalette[400],
  neutralIconActive: glassAccentPalette[600],
  neutralIconDisabled: glassAccentPalette.alpha40,
  neutralIconInDefault: glassAccentPalette[50],
  neutralIconInHover: glassAccentPalette[100],
  neutralIconInActive: glassAccentPalette[200],
  neutralIconInDisabled: glassAccentPalette.alpha10,

  // Info - Purple highlight for informational states
  infoBackgroundDefault: glassHighlightPalette[600],
  infoBackgroundWeak: glassHighlightPalette.alpha10,
  infoBackgroundDisabled: glassHighlightPalette.alpha40,
  infoBackgroundHover: glassHighlightPalette[500],
  infoBackgroundActive: glassHighlightPalette[700],
  infoTextDefault: glassHighlightPalette[200],
  infoTextHover: glassHighlightPalette[100],
  infoTextActive: glassHighlightPalette[300],
  infoTextInDefault: glassHighlightPalette[50],
  infoTextInDisabled: glassHighlightPalette.alpha10,
  infoBorderDefault: glassHighlightPalette[600],
  infoBorderHover: glassHighlightPalette[500],
  infoBorderActive: glassHighlightPalette[700],
  infoBorderDisabled: glassHighlightPalette.alpha40,
  infoBorderWeak: glassHighlightPalette.alpha20,
  infoIconDefault: glassHighlightPalette[500],
  infoIconHover: glassHighlightPalette[400],
  infoIconActive: glassHighlightPalette[600],
  infoIconDisabled: glassHighlightPalette.alpha40,
  infoIconInDefault: glassHighlightPalette[50],
  infoIconInHover: glassHighlightPalette[100],
  infoIconInActive: glassHighlightPalette[200],
  infoIconInDisabled: glassHighlightPalette.alpha10,

  // Inactive - Muted grey on glass
  inactiveBackgroundDefault: greyPalette[600],
  inactiveBackgroundWeak: "rgba(60, 69, 81, 0.10)",
  inactiveBackgroundDisabled: greyPalette["alpha40"],
  inactiveBackgroundHover: greyPalette[500],
  inactiveBackgroundActive: greyPalette[700],
  inactiveTextDefault: greyPalette[200],
  inactiveTextHover: greyPalette[100],
  inactiveTextActive: greyPalette[300],
  inactiveTextInDefault: greyPalette[50],
  inactiveTextInDisabled: greyPalette["alpha40"],
  inactiveBorderDefault: greyPalette[600],
  inactiveBorderHover: greyPalette[500],
  inactiveBorderActive: greyPalette[700],
  inactiveBorderDisabled: greyPalette["alpha40"],
  inactiveBorderWeak: "rgba(60, 69, 81, 0.30)",
  inactiveIconDefault: greyPalette[400],
  inactiveIconHover: greyPalette[300],
  inactiveIconActive: greyPalette[500],
  inactiveIconDisabled: greyPalette["alpha40"],
  inactiveIconInDefault: greyPalette[0],
  inactiveIconInHover: greyPalette[50],
  inactiveIconInActive: greyPalette[100],
  inactiveIconInDisabled: greyPalette["alpha10"],

  // Warning - Orange with glass effect
  warningBackgroundDefault: lightOrangePalette[500],
  warningBackgroundWeak: "rgba(251, 175, 69, 0.10)",
  warningBackgroundHover: lightOrangePalette[400],
  warningBackgroundActive: lightOrangePalette[600],
  warningBackgroundDisabled: lightOrangePalette["alpha40"],
  warningTextDefault: lightOrangePalette[200],
  warningTextHover: lightOrangePalette[100],
  warningTextActive: lightOrangePalette[300],
  warningTextInDefault: lightOrangePalette[50],
  warningTextInDisabled: lightOrangePalette["alpha10"],
  warningBorderDefault: lightOrangePalette[500],
  warningBorderHover: lightOrangePalette[400],
  warningBorderActive: lightOrangePalette[600],
  warningBorderDisabled: lightOrangePalette["alpha40"],
  warningBorderWeak: "rgba(251, 175, 69, 0.30)",
  warningIconDefault: lightOrangePalette[500],
  warningIconHover: lightOrangePalette[400],
  warningIconActive: lightOrangePalette[600],
  warningIconDisabled: lightOrangePalette["alpha40"],
  warningIconInDefault: lightOrangePalette[50],
  warningIconInHover: lightOrangePalette[100],
  warningIconInActive: lightOrangePalette[200],
  warningIconInDisabled: lightOrangePalette["alpha10"],

  // Severe Warning - Deep orange
  severeWarningBackgroundDefault: orangePalette[500],
  severeWarningBackgroundWeak: "rgba(242, 100, 61, 0.10)",
  severeWarningBackgroundHover: orangePalette[400],
  severeWarningBackgroundActive: orangePalette[600],
  severeWarningBackgroundDisabled: orangePalette["alpha40"],
  severeWarningTextDefault: orangePalette[200],
  severeWarningTextHover: orangePalette[100],
  severeWarningTextActive: orangePalette[300],
  severeWarningTextInDefault: orangePalette[50],
  severeWarningTextInDisabled: orangePalette["alpha10"],
  severeWarningBorderDefault: orangePalette[500],
  severeWarningBorderHover: orangePalette[400],
  severeWarningBorderActive: orangePalette[600],
  severeWarningBorderDisabled: orangePalette["alpha40"],
  severeWarningBorderWeak: "rgba(242, 100, 61, 0.30)",
  severeWarningIconDefault: orangePalette[500],
  severeWarningIconHover: orangePalette[400],
  severeWarningIconActive: orangePalette[600],
  severeWarningIconDisabled: orangePalette["alpha40"],
  severeWarningIconInDefault: orangePalette[50],
  severeWarningIconInHover: orangePalette[100],
  severeWarningIconInActive: orangePalette[200],
  severeWarningIconInDisabled: orangePalette["alpha10"],

  // Moderate - Yellow
  moderateBackgroundDefault: yellowPalette[500],
  moderateBackgroundWeak: "rgba(255, 230, 89, 0.10)",
  moderateBackgroundHover: yellowPalette[400],
  moderateBackgroundActive: yellowPalette[600],
  moderateBackgroundDisabled: yellowPalette["alpha40"],
  moderateTextDefault: yellowPalette[900],
  moderateTextHover: yellowPalette[800],
  moderateTextActive: yellowPalette[700],
  moderateTextInDefault: yellowPalette[900],
  moderateTextInDisabled: yellowPalette["alpha10"],
  moderateBorderDefault: yellowPalette[500],
  moderateBorderHover: yellowPalette[400],
  moderateBorderActive: yellowPalette[600],
  moderateBorderDisabled: yellowPalette["alpha40"],
  moderateBorderWeak: "rgba(255, 230, 89, 0.30)",
  moderateIconDefault: yellowPalette[700],
  moderateIconHover: yellowPalette[600],
  moderateIconActive: yellowPalette[800],
  moderateIconDisabled: yellowPalette["alpha40"],
  moderateIconInDefault: yellowPalette[900],
  moderateIconInHover: yellowPalette[800],
  moderateIconInActive: yellowPalette[700],
  moderateIconInDisabled: yellowPalette["alpha10"],

  // Accent Colors - Various accent tints for glass UI
  accentADefault: lavenderPalette[400],
  accentAWeak: "rgba(140, 149, 255, 0.15)",
  accentBDefault: sunsetPalette[300],
  accentBWeak: "rgba(233, 106, 141, 0.15)",
  accentCDefault: sunsetPalette[100],
  accentCWeak: "rgba(243, 172, 162, 0.15)",
  accentDDefault: purplePalette[400],
  accentDWeak: "rgba(192, 128, 255, 0.15)",
  accentEDefault: limePalette[400],
  accentEWeak: "rgba(164, 197, 71, 0.15)",
  accentFDefault: orangePalette[400],
  accentFWeak: "rgba(244, 123, 90, 0.15)",
  accentGDefault: nightPalette[200],
  accentGWeak: "rgba(70, 170, 206, 0.15)",
  accentHDefault: glassAccentPalette[400],
  accentHWeak: "rgba(0, 212, 255, 0.15)",
  accentIDefault: pinkPalette[400],
  accentIWeak: "rgba(242, 99, 140, 0.15)",
  accentJDefault: tealPalette[400],
  accentJWeak: "rgba(62, 203, 209, 0.15)",
};
