/*
 * Copyright 2025 Cisco Systems, Inc. and its affiliates
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { VarsType } from "@/types/vars";
import {
  greenPalette,
  greyPalette,
  lightOrangePalette,
  redPalette,
  lightBluePalette,
  purplePalette,
  orangePalette,
  yellowPalette,
  nightPalette,
  sunsetPalette,
  lavenderPalette,
  limePalette,
  pinkPalette,
  tealPalette,
} from "../color-palette";
import {
  iocNextCyanPalette,
  iocNextBluePalette,
  iocNextSurfacePalette,
  iocNextBackdropPalette,
  iocNextBorderPalette,
  iocNextTextPrimary,
  iocNextTextSecondary,
  iocNextTextTertiary,
  iocNextTextDisabled,
  iocNextPageBackground,
} from "./ioc-next-color-palette";

export const iocNextVars: VarsType = {
  // Brand
  brandOrange: lightOrangePalette[500],
  brandOrangeDark: lightOrangePalette[900],
  brandBlue: iocNextCyanPalette[500],
  brandMidnightBlue: iocNextBackdropPalette[500],
  agentcyYellow: lightOrangePalette[500],
  agentcyBlue: iocNextCyanPalette[500],
  agentcyDarkBlue: iocNextBackdropPalette[900],

  // Text
  baseTextStrong: iocNextTextPrimary,
  baseTextDefault: iocNextTextSecondary,
  baseTextMedium: iocNextTextTertiary,
  baseTextWeak: iocNextTextDisabled,
  baseTextInverse: iocNextBackdropPalette[900],
  baseTextDisabled: iocNextTextDisabled,

  // Background
  baseBackgroundStrong: iocNextBackdropPalette[900],
  baseBackgroundMedium: iocNextSurfacePalette[200],
  baseBackgroundWeak: iocNextSurfacePalette[100],
  baseBackgroundHover: iocNextSurfacePalette[300],

  // Border
  baseBorderDefault: iocNextBorderPalette[300],
  baseBorderStrong: iocNextBorderPalette[500],
  baseBorderMedium: iocNextBorderPalette[200],
  baseBorderWeak: iocNextBorderPalette[100],

  // Brand icon
  brandIconPrimaryDefault: iocNextCyanPalette[500],
  brandIconPrimaryWeak: iocNextCyanPalette[200],
  brandIconPrimaryMedium: iocNextCyanPalette[400],
  brandIconPrimaryStrong: iocNextCyanPalette[700],
  brandIconSecondaryDefault: iocNextBluePalette[500],
  brandIconSecondaryWeak: iocNextBluePalette[400],
  brandIconSecondaryMedium: iocNextBluePalette[500],
  brandIconTertiaryDefault: lightOrangePalette[500],
  brandIconTertiaryWeak: lightOrangePalette[200],
  brandIconTertiaryMedium: lightOrangePalette[400],

  // Brand background
  brandBackgroundPrimaryDefault: iocNextCyanPalette[500],
  brandBackgroundPrimaryWeak: iocNextCyanPalette.alpha10,
  brandBackgroundPrimaryMedium: iocNextCyanPalette.alpha20,
  brandBackgroundSecondaryDefault: iocNextBluePalette[500],
  brandLogoPrimary: iocNextCyanPalette[400],
  brandTextPrimary: iocNextCyanPalette[400],
  brandTextSecondary: iocNextTextPrimary,

  // Control
  controlBackgroundDefault: iocNextSurfacePalette[200],
  controlBackgroundDisabled: iocNextSurfacePalette[50],
  controlBackgroundWeak: iocNextSurfacePalette[300],
  controlBackgroundHover: iocNextSurfacePalette[400],
  controlBackgroundMedium: iocNextSurfacePalette[500],
  controlBorderDefault: iocNextBorderPalette[300],
  controlBorderStrong: iocNextBorderPalette[500],
  controlBorderMedium: iocNextBorderPalette[200],
  controlBorderWeak: iocNextBorderPalette[100],
  controlBorderHover: iocNextCyanPalette[500],
  controlBorderActive: iocNextCyanPalette[600],
  controlBorderNegative: redPalette[500],
  controlBorderDisabled: iocNextBorderPalette[100],
  controlIconDefault: iocNextTextSecondary,
  controlIconStrong: iocNextTextPrimary,
  controlIconMedium: iocNextTextTertiary,
  controlIconWeak: iocNextTextDisabled,
  controlIconHover: iocNextCyanPalette[400],
  controlIconActive: iocNextCyanPalette[500],
  controlIconDisabled: iocNextTextDisabled,

  // Interactive primary (cyan)
  interactivePrimaryDefaultDefault: iocNextCyanPalette[500],
  interactivePrimaryDefaultHover: iocNextCyanPalette[400],
  interactivePrimaryDefaultActive: iocNextCyanPalette[600],
  interactivePrimaryDefaultDisabled: iocNextCyanPalette.alpha40,
  interactivePrimaryWeakDefault: iocNextCyanPalette.alpha10,
  interactivePrimaryWeakHover: iocNextCyanPalette.alpha20,
  interactivePrimaryWeakActive: iocNextCyanPalette.alpha40,
  interactivePrimaryWeakDisabled: iocNextCyanPalette.alpha05,

  // Interactive secondary (blue)
  interactiveSecondaryDefaultDefault: iocNextBluePalette[500],
  interactiveSecondaryDefaultHover: iocNextBluePalette[400],
  interactiveSecondaryDefaultActive: iocNextBluePalette[600],
  interactiveSecondaryDefaultDisabled: "rgba(58,149,255,0.40)",
  interactiveSecondaryWeakDefault: iocNextSurfacePalette[200],
  interactiveSecondaryWeakHover: iocNextSurfacePalette[300],
  interactiveSecondaryWeakActive: iocNextSurfacePalette[400],
  interactiveSecondaryWeakDisabled: iocNextSurfacePalette[100],

  // Interactive inverse
  interactiveInverseBackgroundDefault: "rgba(255,255,255,0.90)",
  interactiveInverseBackgroundHover: "rgba(255,255,255,0.95)",
  interactiveInverseBackgroundActive: "rgba(255,255,255,0.85)",
  interactiveInverseBackgroundDisabled: "rgba(255,255,255,0.40)",
  interactiveInverseTextDefault: iocNextBackdropPalette[900],
  interactiveInverseTextHover: iocNextBackdropPalette[700],
  interactiveInverseTextActive: iocNextBackdropPalette[800],
  interactiveInverseTextDisabled: "rgba(0,0,0,0.30)",

  // Interactive text in
  interactiveTextInDefault: iocNextTextPrimary,
  interactiveTextInHover: iocNextTextPrimary,
  interactiveTextInActive: iocNextTextPrimary,
  interactiveTextInDisabled: iocNextTextDisabled,

  // Interactive tertiary
  interactiveTertiaryDefault: lightOrangePalette[500],
  interactiveTertiaryHover: lightOrangePalette[400],
  interactiveTertiaryActive: lightOrangePalette[600],
  interactiveTertiaryDisabled: lightOrangePalette["alpha40"],

  // Success
  successBackgroundDefault: greenPalette[500],
  successBackgroundDisabled: greenPalette[40],
  successBackgroundHover: greenPalette[400],
  successBackgroundActive: greenPalette[600],
  successBackgroundWeak: "rgba(0, 185, 141, 0.10)",
  successIconActive: greenPalette[600],
  successIconDisabled: greenPalette[40],
  successIconHover: greenPalette[400],
  successIconDefault: greenPalette[500],
  successTextActive: greenPalette[300],
  successTextHover: greenPalette[200],
  successTextDefault: greenPalette[300],
  successTextInDisabled: greenPalette[10],
  successTextInDefault: greyPalette[900],
  successBorderDisabled: greenPalette[40],
  successBorderActive: greenPalette[600],
  successBorderHover: greenPalette[400],
  successBorderDefault: greenPalette[500],
  successBorderWeak: "rgba(0, 185, 141, 0.30)",
  successIconInDisabled: greenPalette[10],
  successIconInActive: greenPalette[200],
  successIconInHover: greenPalette[100],
  successIconInDefault: greenPalette[50],

  // Negative
  negativeBackgroundHover: redPalette[400],
  negativeBackgroundActive: redPalette[600],
  negativeBackgroundDisabled: redPalette["alpha40"],
  negativeBackgroundDefault: redPalette[500],
  negativeBackgroundWeak: "rgba(198, 41, 83, 0.10)",
  negativeTextDefault: redPalette[300],
  negativeTextHover: redPalette[200],
  negativeTextActive: redPalette[400],
  negativeBorderActive: redPalette[600],
  negativeBorderHover: redPalette[400],
  negativeBorderDisabled: redPalette["alpha40"],
  negativeBorderDefault: redPalette[500],
  negativeBorderWeak: "rgba(198, 41, 83, 0.30)",
  negativeIconDisabled: redPalette["alpha40"],
  negativeIconActive: redPalette[600],
  negativeIconHover: redPalette[400],
  negativeIconDefault: redPalette[500],
  negativeTextInDefault: redPalette[50],
  negativeTextInDisabled: redPalette["alpha10"],
  negativeIconInDefault: redPalette[50],
  negativeIconInHover: redPalette[100],
  negativeIconInActive: redPalette[200],
  negativeIconInDisabled: redPalette["alpha10"],

  // Excellent
  excellentBackgroundDefault: lightBluePalette[600],
  excellentBackgroundWeak: "rgba(31, 210, 255, 0.10)",
  excellentBackgroundDisabled: lightBluePalette["alpha40"],
  excellentBackgroundHover: lightBluePalette[500],
  excellentBackgroundActive: lightBluePalette[700],
  excellentTextDefault: lightBluePalette[200],
  excellentTextHover: lightBluePalette[100],
  excellentTextActive: lightBluePalette[300],
  excellentTextInDefault: greyPalette[900],
  excellentTextInDisabled: lightBluePalette["alpha10"],
  excellentBorderDefault: lightBluePalette[600],
  excellentBorderHover: lightBluePalette[500],
  excellentBorderActive: lightBluePalette[700],
  excellentBorderDisabled: lightBluePalette["alpha40"],
  excellentBorderWeak: "rgba(31, 210, 255, 0.30)",
  excellentIconDefault: lightBluePalette[500],
  excellentIconHover: lightBluePalette[400],
  excellentIconActive: lightBluePalette[600],
  excellentIconDisabled: lightBluePalette["alpha40"],
  excellentIconInDefault: lightBluePalette[50],
  excellentIconInHover: lightBluePalette[100],
  excellentIconInActive: lightBluePalette[200],
  excellentIconInDisabled: lightBluePalette["alpha10"],

  // Neutral (cyan family)
  neutralBackgroundDefault: iocNextCyanPalette[600],
  neutralBackgroundWeak: iocNextCyanPalette.alpha10,
  neutralBackgroundDisabled: iocNextCyanPalette.alpha40,
  neutralBackgroundHover: iocNextCyanPalette[500],
  neutralBackgroundActive: iocNextCyanPalette[700],
  neutralTextDefault: iocNextCyanPalette[200],
  neutralTextHover: iocNextCyanPalette[100],
  neutralTextActive: iocNextCyanPalette[300],
  neutralTextInDefault: greyPalette[900],
  neutralTextInDisabled: iocNextCyanPalette.alpha10,
  neutralBorderDefault: iocNextCyanPalette[600],
  neutralBorderHover: iocNextCyanPalette[500],
  neutralBorderActive: iocNextCyanPalette[700],
  neutralBorderDisabled: iocNextCyanPalette.alpha40,
  neutralBorderWeak: iocNextCyanPalette.alpha20,
  neutralIconDefault: iocNextCyanPalette[500],
  neutralIconHover: iocNextCyanPalette[400],
  neutralIconActive: iocNextCyanPalette[600],
  neutralIconDisabled: iocNextCyanPalette.alpha40,
  neutralIconInDefault: iocNextCyanPalette[50],
  neutralIconInHover: iocNextCyanPalette[100],
  neutralIconInActive: iocNextCyanPalette[200],
  neutralIconInDisabled: iocNextCyanPalette.alpha10,

  // Info
  infoBackgroundDefault: iocNextBluePalette[600],
  infoBackgroundWeak: "rgba(58,149,255,0.10)",
  infoBackgroundDisabled: "rgba(58,149,255,0.40)",
  infoBackgroundHover: iocNextBluePalette[500],
  infoBackgroundActive: iocNextBluePalette[600],
  infoTextDefault: "#93C5FD",
  infoTextHover: "#BFDBFE",
  infoTextActive: "#60A5FA",
  infoTextInDefault: greyPalette[900],
  infoTextInDisabled: "rgba(58,149,255,0.10)",
  infoBorderDefault: iocNextBluePalette[600],
  infoBorderHover: iocNextBluePalette[500],
  infoBorderActive: iocNextBluePalette[600],
  infoBorderDisabled: "rgba(58,149,255,0.40)",
  infoBorderWeak: "rgba(58,149,255,0.20)",
  infoIconDefault: iocNextBluePalette[500],
  infoIconHover: iocNextBluePalette[400],
  infoIconActive: iocNextBluePalette[600],
  infoIconDisabled: "rgba(58,149,255,0.40)",
  infoIconInDefault: "#EFF6FF",
  infoIconInHover: "#BFDBFE",
  infoIconInActive: "#93C5FD",
  infoIconInDisabled: "rgba(58,149,255,0.10)",

  // Inactive
  inactiveBackgroundDefault: greyPalette[600],
  inactiveBackgroundWeak: "rgba(60, 69, 81, 0.10)",
  inactiveBackgroundDisabled: greyPalette["alpha40"],
  inactiveBackgroundHover: greyPalette[500],
  inactiveBackgroundActive: greyPalette[700],
  inactiveTextDefault: greyPalette[200],
  inactiveTextHover: greyPalette[100],
  inactiveTextActive: greyPalette[300],
  inactiveTextInDefault: greyPalette[50],
  inactiveTextInDisabled: greyPalette["alpha40"],
  inactiveBorderDefault: greyPalette[600],
  inactiveBorderHover: greyPalette[500],
  inactiveBorderActive: greyPalette[700],
  inactiveBorderDisabled: greyPalette["alpha40"],
  inactiveBorderWeak: "rgba(60, 69, 81, 0.30)",
  inactiveIconDefault: greyPalette[400],
  inactiveIconHover: greyPalette[300],
  inactiveIconActive: greyPalette[500],
  inactiveIconDisabled: greyPalette["alpha40"],
  inactiveIconInDefault: greyPalette[0],
  inactiveIconInHover: greyPalette[50],
  inactiveIconInActive: greyPalette[100],
  inactiveIconInDisabled: greyPalette["alpha10"],

  // Warning
  warningBackgroundDefault: lightOrangePalette[500],
  warningBackgroundWeak: "rgba(251, 175, 69, 0.10)",
  warningBackgroundHover: lightOrangePalette[400],
  warningBackgroundActive: lightOrangePalette[600],
  warningBackgroundDisabled: lightOrangePalette["alpha40"],
  warningTextDefault: lightOrangePalette[200],
  warningTextHover: lightOrangePalette[100],
  warningTextActive: lightOrangePalette[300],
  warningTextInDefault: greyPalette[900],
  warningTextInDisabled: lightOrangePalette["alpha10"],
  warningBorderDefault: lightOrangePalette[500],
  warningBorderHover: lightOrangePalette[400],
  warningBorderActive: lightOrangePalette[600],
  warningBorderDisabled: lightOrangePalette["alpha40"],
  warningBorderWeak: "rgba(251, 175, 69, 0.30)",
  warningIconDefault: lightOrangePalette[500],
  warningIconHover: lightOrangePalette[400],
  warningIconActive: lightOrangePalette[600],
  warningIconDisabled: lightOrangePalette["alpha40"],
  warningIconInDefault: lightOrangePalette[50],
  warningIconInHover: lightOrangePalette[100],
  warningIconInActive: lightOrangePalette[200],
  warningIconInDisabled: lightOrangePalette["alpha10"],

  // Severe warning
  severeWarningBackgroundDefault: orangePalette[500],
  severeWarningBackgroundWeak: "rgba(242, 100, 61, 0.10)",
  severeWarningBackgroundHover: orangePalette[400],
  severeWarningBackgroundActive: orangePalette[600],
  severeWarningBackgroundDisabled: orangePalette["alpha40"],
  severeWarningTextDefault: orangePalette[200],
  severeWarningTextHover: orangePalette[100],
  severeWarningTextActive: orangePalette[300],
  severeWarningTextInDefault: greyPalette[900],
  severeWarningTextInDisabled: orangePalette["alpha10"],
  severeWarningBorderDefault: orangePalette[500],
  severeWarningBorderHover: orangePalette[400],
  severeWarningBorderActive: orangePalette[600],
  severeWarningBorderDisabled: orangePalette["alpha40"],
  severeWarningBorderWeak: "rgba(242, 100, 61, 0.30)",
  severeWarningIconDefault: orangePalette[500],
  severeWarningIconHover: orangePalette[400],
  severeWarningIconActive: orangePalette[600],
  severeWarningIconDisabled: orangePalette["alpha40"],
  severeWarningIconInDefault: orangePalette[50],
  severeWarningIconInHover: orangePalette[100],
  severeWarningIconInActive: orangePalette[200],
  severeWarningIconInDisabled: orangePalette["alpha10"],

  // Moderate
  moderateBackgroundDefault: yellowPalette[500],
  moderateBackgroundWeak: "rgba(255, 230, 89, 0.10)",
  moderateBackgroundHover: yellowPalette[400],
  moderateBackgroundActive: yellowPalette[600],
  moderateBackgroundDisabled: yellowPalette["alpha40"],
  moderateTextDefault: yellowPalette[900],
  moderateTextHover: yellowPalette[800],
  moderateTextActive: yellowPalette[700],
  moderateTextInDefault: greyPalette[900],
  moderateTextInDisabled: yellowPalette["alpha10"],
  moderateBorderDefault: yellowPalette[500],
  moderateBorderHover: yellowPalette[400],
  moderateBorderActive: yellowPalette[600],
  moderateBorderDisabled: yellowPalette["alpha40"],
  moderateBorderWeak: "rgba(255, 230, 89, 0.30)",
  moderateIconDefault: yellowPalette[700],
  moderateIconHover: yellowPalette[600],
  moderateIconActive: yellowPalette[800],
  moderateIconDisabled: yellowPalette["alpha40"],
  moderateIconInDefault: yellowPalette[900],
  moderateIconInHover: yellowPalette[800],
  moderateIconInActive: yellowPalette[700],
  moderateIconInDisabled: yellowPalette["alpha10"],

  // Accent colors
  accentADefault: lavenderPalette[400],
  accentAWeak: "rgba(140, 149, 255, 0.15)",
  accentBDefault: sunsetPalette[300],
  accentBWeak: "rgba(233, 106, 141, 0.15)",
  accentCDefault: sunsetPalette[100],
  accentCWeak: "rgba(243, 172, 162, 0.15)",
  accentDDefault: purplePalette[400],
  accentDWeak: "rgba(192, 128, 255, 0.15)",
  accentEDefault: limePalette[400],
  accentEWeak: "rgba(164, 197, 71, 0.15)",
  accentFDefault: orangePalette[400],
  accentFWeak: "rgba(244, 123, 90, 0.15)",
  accentGDefault: nightPalette[200],
  accentGWeak: "rgba(70, 170, 206, 0.15)",
  accentHDefault: iocNextCyanPalette[400],
  accentHWeak: iocNextCyanPalette.alpha10,
  accentIDefault: pinkPalette[400],
  accentIWeak: "rgba(242, 99, 140, 0.15)",
  accentJDefault: tealPalette[400],
  accentJWeak: "rgba(62, 203, 209, 0.15)",

  // Shape — border radius
  borderRadiusSm: "4px",
  borderRadiusLg: "8px",
  borderRadius4xl: "20px",
  // Shape — border width
  borderWidthDefault: "1px",
  borderWidthStrong: "4px",

  // Gradients
  gradientPrimary: `linear-gradient(180deg, ${iocNextCyanPalette[400]} 0%, ${iocNextCyanPalette[600]} 100%)`,
  gradientSecondary: `linear-gradient(180deg, ${iocNextBluePalette[500]} 0%, ${iocNextBluePalette[600]} 100%)`,
  gradientNegative: `linear-gradient(180deg, ${redPalette[400]} 0%, ${redPalette[500]} 100%)`,
  gradientBrand: `linear-gradient(135deg, ${iocNextCyanPalette[400]} 0%, ${iocNextBluePalette[500]} 100%)`,
  gradientPage: iocNextPageBackground,

  // Glows — 3-layer bloom box-shadows for OXP dark surfaces
  glowPrimary: `0 0 6px ${iocNextCyanPalette[500]}CC, 0 0 16px ${iocNextCyanPalette[500]}77, 0 0 28px ${iocNextCyanPalette[500]}33`,
  glowSecondary: `0 0 6px ${iocNextBluePalette[500]}CC, 0 0 16px ${iocNextBluePalette[500]}77, 0 0 28px ${iocNextBluePalette[500]}33`,
  glowSuccess: `0 0 6px ${greenPalette[500]}CC, 0 0 16px ${greenPalette[500]}77, 0 0 28px ${greenPalette[500]}33`,
  glowWarning: `0 0 6px ${lightOrangePalette[500]}CC, 0 0 16px ${lightOrangePalette[500]}77, 0 0 28px ${lightOrangePalette[500]}33`,
  glowNegative: `0 0 6px ${redPalette[500]}CC, 0 0 16px ${redPalette[500]}77, 0 0 28px ${redPalette[500]}33`,
  glowSevere: `0 0 6px ${orangePalette[500]}CC, 0 0 16px ${orangePalette[500]}77, 0 0 28px ${orangePalette[500]}33`,
  glowExcellent: `0 0 6px ${lightBluePalette[500]}CC, 0 0 16px ${lightBluePalette[500]}77, 0 0 28px ${lightBluePalette[500]}33`,
  glowNeutral: `0 0 6px ${iocNextCyanPalette[600]}99, 0 0 14px ${iocNextCyanPalette[600]}44`,
};
