/*
 * Copyright 2025 Cisco Systems, Inc. and its affiliates
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { VarsType } from "@/types/vars";
import {
  greenPalette,
  greyPalette,
  lightBluePalette,
  lightOrangePalette,
  redPalette,
  purplePalette,
  orangePalette,
  yellowPalette,
  nightPalette,
  sunsetPalette,
  lavenderPalette,
  limePalette,
  pinkPalette,
  tealPalette,
} from "../color-palette";
import {
  iocNextCyanPalette,
  iocNextBluePalette,
} from "./ioc-next-color-palette";
import {
  iocNextLightSurfacePalette,
  iocNextLightBorderPalette,
  iocNextLightTextPrimary,
  iocNextLightTextSecondary,
  iocNextLightTextTertiary,
  iocNextLightTextDisabled,
  iocNextLightPageBackground,
} from "./ioc-next-light-color-palette";

export const iocNextLightVars: VarsType = {
  // Brand
  brandOrange: lightOrangePalette[500],
  brandOrangeDark: lightOrangePalette[900],
  brandBlue: iocNextCyanPalette[500],
  brandMidnightBlue: "#0C1B30",
  agentcyYellow: lightOrangePalette[500],
  agentcyBlue: iocNextCyanPalette[500],
  agentcyDarkBlue: "#0C1B30",

  // Text
  baseTextStrong: iocNextLightTextPrimary,
  baseTextDefault: iocNextLightTextSecondary,
  baseTextMedium: iocNextLightTextTertiary,
  baseTextWeak: iocNextLightTextDisabled,
  baseTextInverse: "#FFFFFF",
  baseTextDisabled: iocNextLightTextDisabled,

  // Background
  baseBackgroundStrong: iocNextLightSurfacePalette[50],
  baseBackgroundMedium: iocNextLightSurfacePalette[200],
  baseBackgroundWeak: iocNextLightSurfacePalette[100],
  baseBackgroundHover: iocNextLightSurfacePalette[300],

  // Border
  baseBorderDefault: iocNextLightBorderPalette[300],
  baseBorderStrong: iocNextLightBorderPalette[500],
  baseBorderMedium: iocNextLightBorderPalette[200],
  baseBorderWeak: iocNextLightBorderPalette[100],

  // Brand icon
  brandIconPrimaryDefault: iocNextCyanPalette[600],
  brandIconPrimaryWeak: iocNextCyanPalette[200],
  brandIconPrimaryMedium: iocNextCyanPalette[500],
  brandIconPrimaryStrong: iocNextCyanPalette[700],
  brandIconSecondaryDefault: iocNextBluePalette[500],
  brandIconSecondaryWeak: iocNextBluePalette[400],
  brandIconSecondaryMedium: iocNextBluePalette[500],
  brandIconTertiaryDefault: lightOrangePalette[500],
  brandIconTertiaryWeak: lightOrangePalette[200],
  brandIconTertiaryMedium: lightOrangePalette[400],

  // Brand background
  brandBackgroundPrimaryDefault: iocNextCyanPalette[500],
  brandBackgroundPrimaryWeak: iocNextCyanPalette.alpha10,
  brandBackgroundPrimaryMedium: iocNextCyanPalette.alpha20,
  brandBackgroundSecondaryDefault: iocNextBluePalette[500],
  brandLogoPrimary: iocNextCyanPalette[600],
  brandTextPrimary: iocNextCyanPalette[700],
  brandTextSecondary: iocNextLightTextPrimary,

  // Control
  controlBackgroundDefault: iocNextLightSurfacePalette[50],
  controlBackgroundDisabled: iocNextLightSurfacePalette[100],
  controlBackgroundWeak: iocNextLightSurfacePalette[200],
  controlBackgroundHover: iocNextLightSurfacePalette[200],
  controlBackgroundMedium: iocNextLightSurfacePalette[300],
  controlBorderDefault: iocNextLightBorderPalette[300],
  controlBorderStrong: iocNextLightBorderPalette[500],
  controlBorderMedium: iocNextLightBorderPalette[200],
  controlBorderWeak: iocNextLightBorderPalette[100],
  controlBorderHover: iocNextCyanPalette[500],
  controlBorderActive: iocNextCyanPalette[600],
  controlBorderNegative: redPalette[500],
  controlBorderDisabled: iocNextLightBorderPalette[100],
  controlIconDefault: iocNextLightTextSecondary,
  controlIconStrong: iocNextLightTextPrimary,
  controlIconMedium: iocNextLightTextTertiary,
  controlIconWeak: iocNextLightTextDisabled,
  controlIconHover: iocNextCyanPalette[600],
  controlIconActive: iocNextCyanPalette[700],
  controlIconDisabled: iocNextLightTextDisabled,

  // Interactive primary (cyan)
  interactivePrimaryDefaultDefault: iocNextCyanPalette[500],
  interactivePrimaryDefaultHover: iocNextCyanPalette[600],
  interactivePrimaryDefaultActive: iocNextCyanPalette[700],
  interactivePrimaryDefaultDisabled: iocNextCyanPalette.alpha40,
  interactivePrimaryWeakDefault: iocNextCyanPalette.alpha10,
  interactivePrimaryWeakHover: iocNextCyanPalette.alpha20,
  interactivePrimaryWeakActive: iocNextCyanPalette.alpha40,
  interactivePrimaryWeakDisabled: iocNextCyanPalette.alpha05,

  // Interactive secondary (blue)
  interactiveSecondaryDefaultDefault: iocNextBluePalette[500],
  interactiveSecondaryDefaultHover: iocNextBluePalette[600],
  interactiveSecondaryDefaultActive: iocNextBluePalette[600],
  interactiveSecondaryDefaultDisabled: "rgba(58,149,255,0.40)",
  interactiveSecondaryWeakDefault: iocNextLightSurfacePalette[200],
  interactiveSecondaryWeakHover: iocNextLightSurfacePalette[300],
  interactiveSecondaryWeakActive: iocNextLightSurfacePalette[400],
  interactiveSecondaryWeakDisabled: iocNextLightSurfacePalette[100],

  // Interactive inverse
  interactiveInverseBackgroundDefault: "rgba(12,27,48,0.90)",
  interactiveInverseBackgroundHover: "rgba(12,27,48,0.95)",
  interactiveInverseBackgroundActive: "rgba(12,27,48,0.85)",
  interactiveInverseBackgroundDisabled: "rgba(12,27,48,0.40)",
  interactiveInverseTextDefault: "#FFFFFF",
  interactiveInverseTextHover: "rgba(255,255,255,0.90)",
  interactiveInverseTextActive: "rgba(255,255,255,0.95)",
  interactiveInverseTextDisabled: "rgba(255,255,255,0.50)",

  // Interactive text in
  interactiveTextInDefault: "#FFFFFF",
  interactiveTextInHover: "#FFFFFF",
  interactiveTextInActive: "#FFFFFF",
  interactiveTextInDisabled: iocNextLightTextDisabled,

  // Interactive tertiary
  interactiveTertiaryDefault: lightOrangePalette[500],
  interactiveTertiaryHover: lightOrangePalette[600],
  interactiveTertiaryActive: lightOrangePalette[700],
  interactiveTertiaryDisabled: lightOrangePalette["alpha40"],

  // Success
  successBackgroundDefault: greenPalette[500],
  successBackgroundDisabled: greenPalette[40],
  successBackgroundHover: greenPalette[600],
  successBackgroundActive: greenPalette[700],
  successBackgroundWeak: "rgba(0, 185, 141, 0.10)",
  successIconActive: greenPalette[700],
  successIconDisabled: greenPalette[40],
  successIconHover: greenPalette[600],
  successIconDefault: greenPalette[500],
  successTextActive: greenPalette[700],
  successTextHover: greenPalette[600],
  successTextDefault: greenPalette[600],
  successTextInDisabled: greenPalette[10],
  successTextInDefault: "#FFFFFF",
  successBorderDisabled: greenPalette[40],
  successBorderActive: greenPalette[700],
  successBorderHover: greenPalette[600],
  successBorderDefault: greenPalette[500],
  successBorderWeak: "rgba(0, 185, 141, 0.30)",
  successIconInDisabled: greenPalette[10],
  successIconInActive: greenPalette[200],
  successIconInHover: greenPalette[100],
  successIconInDefault: greenPalette[50],

  // Negative
  negativeBackgroundHover: redPalette[600],
  negativeBackgroundActive: redPalette[700],
  negativeBackgroundDisabled: redPalette["alpha40"],
  negativeBackgroundDefault: redPalette[500],
  negativeBackgroundWeak: "rgba(198, 41, 83, 0.10)",
  negativeTextDefault: redPalette[600],
  negativeTextHover: redPalette[700],
  negativeTextActive: redPalette[700],
  negativeBorderActive: redPalette[700],
  negativeBorderHover: redPalette[600],
  negativeBorderDisabled: redPalette["alpha40"],
  negativeBorderDefault: redPalette[500],
  negativeBorderWeak: "rgba(198, 41, 83, 0.30)",
  negativeIconDisabled: redPalette["alpha40"],
  negativeIconActive: redPalette[700],
  negativeIconHover: redPalette[600],
  negativeIconDefault: redPalette[500],
  negativeTextInDefault: "#FFFFFF",
  negativeTextInDisabled: redPalette["alpha10"],
  negativeIconInDefault: redPalette[50],
  negativeIconInHover: redPalette[100],
  negativeIconInActive: redPalette[200],
  negativeIconInDisabled: redPalette["alpha10"],

  // Excellent
  excellentBackgroundDefault: lightBluePalette[600],
  excellentBackgroundWeak: "rgba(31, 210, 255, 0.10)",
  excellentBackgroundDisabled: lightBluePalette["alpha40"],
  excellentBackgroundHover: lightBluePalette[700],
  excellentBackgroundActive: lightBluePalette[800],
  excellentTextDefault: lightBluePalette[700],
  excellentTextHover: lightBluePalette[800],
  excellentTextActive: lightBluePalette[900],
  excellentTextInDefault: greyPalette[900],
  excellentTextInDisabled: lightBluePalette["alpha10"],
  excellentBorderDefault: lightBluePalette[600],
  excellentBorderHover: lightBluePalette[700],
  excellentBorderActive: lightBluePalette[800],
  excellentBorderDisabled: lightBluePalette["alpha40"],
  excellentBorderWeak: "rgba(31, 210, 255, 0.30)",
  excellentIconDefault: lightBluePalette[600],
  excellentIconHover: lightBluePalette[700],
  excellentIconActive: lightBluePalette[800],
  excellentIconDisabled: lightBluePalette["alpha40"],
  excellentIconInDefault: lightBluePalette[50],
  excellentIconInHover: lightBluePalette[100],
  excellentIconInActive: lightBluePalette[200],
  excellentIconInDisabled: lightBluePalette["alpha10"],

  // Neutral (cyan family)
  neutralBackgroundDefault: iocNextCyanPalette[500],
  neutralBackgroundWeak: iocNextCyanPalette.alpha10,
  neutralBackgroundDisabled: iocNextCyanPalette.alpha40,
  neutralBackgroundHover: iocNextCyanPalette[600],
  neutralBackgroundActive: iocNextCyanPalette[700],
  neutralTextDefault: iocNextCyanPalette[700],
  neutralTextHover: iocNextCyanPalette[800],
  neutralTextActive: iocNextCyanPalette[800],
  neutralTextInDefault: greyPalette[900],
  neutralTextInDisabled: iocNextCyanPalette.alpha10,
  neutralBorderDefault: iocNextCyanPalette[500],
  neutralBorderHover: iocNextCyanPalette[600],
  neutralBorderActive: iocNextCyanPalette[700],
  neutralBorderDisabled: iocNextCyanPalette.alpha40,
  neutralBorderWeak: iocNextCyanPalette.alpha20,
  neutralIconDefault: iocNextCyanPalette[600],
  neutralIconHover: iocNextCyanPalette[700],
  neutralIconActive: iocNextCyanPalette[800],
  neutralIconDisabled: iocNextCyanPalette.alpha40,
  neutralIconInDefault: iocNextCyanPalette[50],
  neutralIconInHover: iocNextCyanPalette[100],
  neutralIconInActive: iocNextCyanPalette[200],
  neutralIconInDisabled: iocNextCyanPalette.alpha10,

  // Info
  infoBackgroundDefault: iocNextBluePalette[500],
  infoBackgroundWeak: "rgba(58,149,255,0.10)",
  infoBackgroundDisabled: "rgba(58,149,255,0.40)",
  infoBackgroundHover: iocNextBluePalette[600],
  infoBackgroundActive: iocNextBluePalette[600],
  infoTextDefault: iocNextBluePalette[600],
  infoTextHover: "#1E6FD9",
  infoTextActive: "#1860C8",
  infoTextInDefault: greyPalette[900],
  infoTextInDisabled: "rgba(58,149,255,0.10)",
  infoBorderDefault: iocNextBluePalette[500],
  infoBorderHover: iocNextBluePalette[600],
  infoBorderActive: iocNextBluePalette[600],
  infoBorderDisabled: "rgba(58,149,255,0.40)",
  infoBorderWeak: "rgba(58,149,255,0.20)",
  infoIconDefault: iocNextBluePalette[500],
  infoIconHover: iocNextBluePalette[600],
  infoIconActive: iocNextBluePalette[600],
  infoIconDisabled: "rgba(58,149,255,0.40)",
  infoIconInDefault: "#EFF6FF",
  infoIconInHover: "#BFDBFE",
  infoIconInActive: "#93C5FD",
  infoIconInDisabled: "rgba(58,149,255,0.10)",

  // Inactive
  inactiveBackgroundDefault: greyPalette[300],
  inactiveBackgroundWeak: "rgba(60, 69, 81, 0.10)",
  inactiveBackgroundDisabled: greyPalette["alpha40"],
  inactiveBackgroundHover: greyPalette[400],
  inactiveBackgroundActive: greyPalette[500],
  inactiveTextDefault: greyPalette[600],
  inactiveTextHover: greyPalette[700],
  inactiveTextActive: greyPalette[700],
  inactiveTextInDefault: greyPalette[900],
  inactiveTextInDisabled: greyPalette["alpha40"],
  inactiveBorderDefault: greyPalette[300],
  inactiveBorderHover: greyPalette[400],
  inactiveBorderActive: greyPalette[500],
  inactiveBorderDisabled: greyPalette["alpha40"],
  inactiveBorderWeak: "rgba(60, 69, 81, 0.20)",
  inactiveIconDefault: greyPalette[400],
  inactiveIconHover: greyPalette[500],
  inactiveIconActive: greyPalette[600],
  inactiveIconDisabled: greyPalette["alpha40"],
  inactiveIconInDefault: greyPalette[0],
  inactiveIconInHover: greyPalette[50],
  inactiveIconInActive: greyPalette[100],
  inactiveIconInDisabled: greyPalette["alpha10"],

  // Warning
  warningBackgroundDefault: lightOrangePalette[500],
  warningBackgroundWeak: "rgba(251, 175, 69, 0.10)",
  warningBackgroundHover: lightOrangePalette[600],
  warningBackgroundActive: lightOrangePalette[700],
  warningBackgroundDisabled: lightOrangePalette["alpha40"],
  warningTextDefault: lightOrangePalette[700],
  warningTextHover: lightOrangePalette[800],
  warningTextActive: lightOrangePalette[800],
  warningTextInDefault: greyPalette[900],
  warningTextInDisabled: lightOrangePalette["alpha10"],
  warningBorderDefault: lightOrangePalette[500],
  warningBorderHover: lightOrangePalette[600],
  warningBorderActive: lightOrangePalette[700],
  warningBorderDisabled: lightOrangePalette["alpha40"],
  warningBorderWeak: "rgba(251, 175, 69, 0.30)",
  warningIconDefault: lightOrangePalette[500],
  warningIconHover: lightOrangePalette[600],
  warningIconActive: lightOrangePalette[700],
  warningIconDisabled: lightOrangePalette["alpha40"],
  warningIconInDefault: lightOrangePalette[50],
  warningIconInHover: lightOrangePalette[100],
  warningIconInActive: lightOrangePalette[200],
  warningIconInDisabled: lightOrangePalette["alpha10"],

  // Severe warning
  severeWarningBackgroundDefault: orangePalette[500],
  severeWarningBackgroundWeak: "rgba(242, 100, 61, 0.10)",
  severeWarningBackgroundHover: orangePalette[600],
  severeWarningBackgroundActive: orangePalette[700],
  severeWarningBackgroundDisabled: orangePalette["alpha40"],
  severeWarningTextDefault: orangePalette[700],
  severeWarningTextHover: orangePalette[800],
  severeWarningTextActive: orangePalette[800],
  severeWarningTextInDefault: greyPalette[900],
  severeWarningTextInDisabled: orangePalette["alpha10"],
  severeWarningBorderDefault: orangePalette[500],
  severeWarningBorderHover: orangePalette[600],
  severeWarningBorderActive: orangePalette[700],
  severeWarningBorderDisabled: orangePalette["alpha40"],
  severeWarningBorderWeak: "rgba(242, 100, 61, 0.30)",
  severeWarningIconDefault: orangePalette[500],
  severeWarningIconHover: orangePalette[600],
  severeWarningIconActive: orangePalette[700],
  severeWarningIconDisabled: orangePalette["alpha40"],
  severeWarningIconInDefault: orangePalette[50],
  severeWarningIconInHover: orangePalette[100],
  severeWarningIconInActive: orangePalette[200],
  severeWarningIconInDisabled: orangePalette["alpha10"],

  // Moderate
  moderateBackgroundDefault: yellowPalette[500],
  moderateBackgroundWeak: "rgba(255, 230, 89, 0.10)",
  moderateBackgroundHover: yellowPalette[600],
  moderateBackgroundActive: yellowPalette[700],
  moderateBackgroundDisabled: yellowPalette["alpha40"],
  moderateTextDefault: yellowPalette[900],
  moderateTextHover: yellowPalette[800],
  moderateTextActive: yellowPalette[800],
  moderateTextInDefault: greyPalette[900],
  moderateTextInDisabled: yellowPalette["alpha10"],
  moderateBorderDefault: yellowPalette[500],
  moderateBorderHover: yellowPalette[600],
  moderateBorderActive: yellowPalette[700],
  moderateBorderDisabled: yellowPalette["alpha40"],
  moderateBorderWeak: "rgba(255, 230, 89, 0.30)",
  moderateIconDefault: yellowPalette[700],
  moderateIconHover: yellowPalette[800],
  moderateIconActive: yellowPalette[800],
  moderateIconDisabled: yellowPalette["alpha40"],
  moderateIconInDefault: yellowPalette[900],
  moderateIconInHover: yellowPalette[800],
  moderateIconInActive: yellowPalette[700],
  moderateIconInDisabled: yellowPalette["alpha10"],

  // Accent colors
  accentADefault: lavenderPalette[600],
  accentAWeak: "rgba(140, 149, 255, 0.12)",
  accentBDefault: sunsetPalette[400],
  accentBWeak: "rgba(233, 106, 141, 0.12)",
  accentCDefault: sunsetPalette[200],
  accentCWeak: "rgba(243, 172, 162, 0.12)",
  accentDDefault: purplePalette[500],
  accentDWeak: "rgba(192, 128, 255, 0.12)",
  accentEDefault: limePalette[600],
  accentEWeak: "rgba(164, 197, 71, 0.12)",
  accentFDefault: orangePalette[500],
  accentFWeak: "rgba(244, 123, 90, 0.12)",
  accentGDefault: nightPalette[400],
  accentGWeak: "rgba(70, 170, 206, 0.12)",
  accentHDefault: iocNextCyanPalette[600],
  accentHWeak: iocNextCyanPalette.alpha10,
  accentIDefault: pinkPalette[500],
  accentIWeak: "rgba(242, 99, 140, 0.12)",
  accentJDefault: tealPalette[500],
  accentJWeak: "rgba(62, 203, 209, 0.12)",

  // Shape — border radius (OXP: distinctly larger / rounder than other themes)
  borderRadiusSm: "8px",
  borderRadiusLg: "16px",
  borderRadius4xl: "28px",
  // Shape — border width
  borderWidthDefault: "1px",
  borderWidthStrong: "4px",

  // Gradients
  gradientPrimary: `linear-gradient(180deg, ${iocNextCyanPalette[400]} 0%, ${iocNextCyanPalette[600]} 100%)`,
  gradientSecondary: `linear-gradient(180deg, ${iocNextBluePalette[500]} 0%, ${iocNextBluePalette[600]} 100%)`,
  gradientNegative: `linear-gradient(180deg, ${redPalette[400]} 0%, ${redPalette[500]} 100%)`,
  gradientBrand: `linear-gradient(135deg, ${iocNextCyanPalette[400]} 0%, ${iocNextBluePalette[500]} 100%)`,
  gradientPage: iocNextLightPageBackground,

  // Glows — very subtle on light backgrounds
  glowPrimary: `0 0 4px ${iocNextCyanPalette[500]}55, 0 0 10px ${iocNextCyanPalette[500]}22`,
  glowSecondary: `0 0 4px ${iocNextBluePalette[500]}55, 0 0 10px ${iocNextBluePalette[500]}22`,
  glowSuccess: `0 0 4px ${greenPalette[500]}55, 0 0 10px ${greenPalette[500]}22`,
  glowWarning: `0 0 4px ${lightOrangePalette[500]}55, 0 0 10px ${lightOrangePalette[500]}22`,
  glowNegative: `0 0 4px ${redPalette[500]}55, 0 0 10px ${redPalette[500]}22`,
  glowSevere: `0 0 4px ${orangePalette[500]}55, 0 0 10px ${orangePalette[500]}22`,
  glowExcellent: `0 0 4px ${lightBluePalette[500]}55, 0 0 10px ${lightBluePalette[500]}22`,
  glowNeutral: `0 0 3px ${iocNextCyanPalette[600]}44, 0 0 8px ${iocNextCyanPalette[600]}18`,
};
