/*
 * Copyright 2025 Cisco Systems, Inc. and its affiliates
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { VarsType } from "@/types/vars";
import {
  greenPalette,
  greyPalette,
  lightBluePalette,
  lightOrangePalette,
  redPalette,
  purplePalette,
  orangePalette,
  yellowPalette,
  nightPalette,
  sunsetPalette,
  lavenderPalette,
  limePalette,
  pinkPalette,
  tealPalette,
} from "../color-palette";
import { iocTealPalette, iocBluePalette } from "./ioc-color-palette";
import {
  iocLightSurfacePalette,
  iocLightBorderPalette,
  iocLightTextPrimary,
  iocLightTextSecondary,
  iocLightTextTertiary,
  iocLightTextDisabled,
  iocLightPageBackground,
} from "./ioc-light-color-palette";

export const iocLightVars: VarsType = {
  // Brand
  brandOrange: lightOrangePalette[500],
  brandOrangeDark: lightOrangePalette[900],
  brandBlue: iocTealPalette[500],
  brandMidnightBlue: "#0A1628",
  agentcyYellow: lightOrangePalette[500],
  agentcyBlue: iocTealPalette[500],
  agentcyDarkBlue: "#0A1628",

  // Text
  baseTextStrong: iocLightTextPrimary,
  baseTextDefault: iocLightTextSecondary,
  baseTextMedium: iocLightTextTertiary,
  baseTextWeak: iocLightTextDisabled,
  baseTextInverse: "#FFFFFF",
  baseTextDisabled: iocLightTextDisabled,

  // Background
  baseBackgroundStrong: iocLightSurfacePalette[50],
  baseBackgroundMedium: iocLightSurfacePalette[200],
  baseBackgroundWeak: iocLightSurfacePalette[100],
  baseBackgroundHover: iocLightSurfacePalette[300],

  // Border
  baseBorderDefault: iocLightBorderPalette[300],
  baseBorderStrong: iocLightBorderPalette[500],
  baseBorderMedium: iocLightBorderPalette[200],
  baseBorderWeak: iocLightBorderPalette[100],

  // Brand icon
  brandIconPrimaryDefault: iocTealPalette[600],
  brandIconPrimaryWeak: iocTealPalette[200],
  brandIconPrimaryMedium: iocTealPalette[500],
  brandIconPrimaryStrong: iocTealPalette[700],
  brandIconSecondaryDefault: iocBluePalette[500],
  brandIconSecondaryWeak: iocBluePalette[400],
  brandIconSecondaryMedium: iocBluePalette[500],
  brandIconTertiaryDefault: lightOrangePalette[500],
  brandIconTertiaryWeak: lightOrangePalette[200],
  brandIconTertiaryMedium: lightOrangePalette[400],

  // Brand background
  brandBackgroundPrimaryDefault: iocTealPalette[500],
  brandBackgroundPrimaryWeak: iocTealPalette.alpha10,
  brandBackgroundPrimaryMedium: iocTealPalette.alpha20,
  brandBackgroundSecondaryDefault: iocBluePalette[500],
  brandLogoPrimary: iocTealPalette[600],
  brandTextPrimary: iocTealPalette[700],
  brandTextSecondary: iocLightTextPrimary,

  // Control
  controlBackgroundDefault: iocLightSurfacePalette[50],
  controlBackgroundDisabled: iocLightSurfacePalette[100],
  controlBackgroundWeak: iocLightSurfacePalette[200],
  controlBackgroundHover: iocLightSurfacePalette[200],
  controlBackgroundMedium: iocLightSurfacePalette[300],
  controlBorderDefault: iocLightBorderPalette[300],
  controlBorderStrong: iocLightBorderPalette[500],
  controlBorderMedium: iocLightBorderPalette[200],
  controlBorderWeak: iocLightBorderPalette[100],
  controlBorderHover: iocTealPalette[500],
  controlBorderActive: iocTealPalette[600],
  controlBorderNegative: redPalette[500],
  controlBorderDisabled: iocLightBorderPalette[100],
  controlIconDefault: iocLightTextSecondary,
  controlIconStrong: iocLightTextPrimary,
  controlIconMedium: iocLightTextTertiary,
  controlIconWeak: iocLightTextDisabled,
  controlIconHover: iocTealPalette[600],
  controlIconActive: iocTealPalette[700],
  controlIconDisabled: iocLightTextDisabled,

  // Interactive primary (teal)
  interactivePrimaryDefaultDefault: iocTealPalette[500],
  interactivePrimaryDefaultHover: iocTealPalette[600],
  interactivePrimaryDefaultActive: iocTealPalette[700],
  interactivePrimaryDefaultDisabled: iocTealPalette.alpha40,
  interactivePrimaryWeakDefault: iocTealPalette.alpha10,
  interactivePrimaryWeakHover: iocTealPalette.alpha20,
  interactivePrimaryWeakActive: iocTealPalette.alpha40,
  interactivePrimaryWeakDisabled: iocTealPalette.alpha05,

  // Interactive secondary (blue)
  interactiveSecondaryDefaultDefault: iocBluePalette[500],
  interactiveSecondaryDefaultHover: iocBluePalette[600],
  interactiveSecondaryDefaultActive: iocBluePalette[600],
  interactiveSecondaryDefaultDisabled: "rgba(43,130,246,0.40)",
  interactiveSecondaryWeakDefault: iocLightSurfacePalette[200],
  interactiveSecondaryWeakHover: iocLightSurfacePalette[300],
  interactiveSecondaryWeakActive: iocLightSurfacePalette[400],
  interactiveSecondaryWeakDisabled: iocLightSurfacePalette[100],

  // Interactive inverse
  interactiveInverseBackgroundDefault: "rgba(10,22,40,0.90)",
  interactiveInverseBackgroundHover: "rgba(10,22,40,0.95)",
  interactiveInverseBackgroundActive: "rgba(10,22,40,0.85)",
  interactiveInverseBackgroundDisabled: "rgba(10,22,40,0.40)",
  interactiveInverseTextDefault: "#FFFFFF",
  interactiveInverseTextHover: "rgba(255,255,255,0.90)",
  interactiveInverseTextActive: "rgba(255,255,255,0.95)",
  interactiveInverseTextDisabled: "rgba(255,255,255,0.50)",

  // Interactive text in
  interactiveTextInDefault: "#FFFFFF",
  interactiveTextInHover: "#FFFFFF",
  interactiveTextInActive: "#FFFFFF",
  interactiveTextInDisabled: iocLightTextDisabled,

  // Interactive tertiary
  interactiveTertiaryDefault: lightOrangePalette[500],
  interactiveTertiaryHover: lightOrangePalette[600],
  interactiveTertiaryActive: lightOrangePalette[700],
  interactiveTertiaryDisabled: lightOrangePalette["alpha40"],

  // Success
  successBackgroundDefault: greenPalette[500],
  successBackgroundDisabled: greenPalette[40],
  successBackgroundHover: greenPalette[600],
  successBackgroundActive: greenPalette[700],
  successBackgroundWeak: "rgba(0, 185, 141, 0.10)",
  successIconActive: greenPalette[700],
  successIconDisabled: greenPalette[40],
  successIconHover: greenPalette[600],
  successIconDefault: greenPalette[500],
  successTextActive: greenPalette[700],
  successTextHover: greenPalette[600],
  successTextDefault: greenPalette[600],
  successTextInDisabled: greenPalette[10],
  successTextInDefault: "#FFFFFF",
  successBorderDisabled: greenPalette[40],
  successBorderActive: greenPalette[700],
  successBorderHover: greenPalette[600],
  successBorderDefault: greenPalette[500],
  successBorderWeak: "rgba(0, 185, 141, 0.30)",
  successIconInDisabled: greenPalette[10],
  successIconInActive: greenPalette[200],
  successIconInHover: greenPalette[100],
  successIconInDefault: greenPalette[50],

  // Negative
  negativeBackgroundHover: redPalette[600],
  negativeBackgroundActive: redPalette[700],
  negativeBackgroundDisabled: redPalette["alpha40"],
  negativeBackgroundDefault: redPalette[500],
  negativeBackgroundWeak: "rgba(198, 41, 83, 0.10)",
  negativeTextDefault: redPalette[600],
  negativeTextHover: redPalette[700],
  negativeTextActive: redPalette[700],
  negativeBorderActive: redPalette[700],
  negativeBorderHover: redPalette[600],
  negativeBorderDisabled: redPalette["alpha40"],
  negativeBorderDefault: redPalette[500],
  negativeBorderWeak: "rgba(198, 41, 83, 0.30)",
  negativeIconDisabled: redPalette["alpha40"],
  negativeIconActive: redPalette[700],
  negativeIconHover: redPalette[600],
  negativeIconDefault: redPalette[500],
  negativeTextInDefault: "#FFFFFF",
  negativeTextInDisabled: redPalette["alpha10"],
  negativeIconInDefault: redPalette[50],
  negativeIconInHover: redPalette[100],
  negativeIconInActive: redPalette[200],
  negativeIconInDisabled: redPalette["alpha10"],

  // Excellent
  excellentBackgroundDefault: lightBluePalette[600],
  excellentBackgroundWeak: "rgba(31, 210, 255, 0.10)",
  excellentBackgroundDisabled: lightBluePalette["alpha40"],
  excellentBackgroundHover: lightBluePalette[700],
  excellentBackgroundActive: lightBluePalette[800],
  excellentTextDefault: lightBluePalette[700],
  excellentTextHover: lightBluePalette[800],
  excellentTextActive: lightBluePalette[900],
  excellentTextInDefault: greyPalette[900],
  excellentTextInDisabled: lightBluePalette["alpha10"],
  excellentBorderDefault: lightBluePalette[600],
  excellentBorderHover: lightBluePalette[700],
  excellentBorderActive: lightBluePalette[800],
  excellentBorderDisabled: lightBluePalette["alpha40"],
  excellentBorderWeak: "rgba(31, 210, 255, 0.30)",
  excellentIconDefault: lightBluePalette[600],
  excellentIconHover: lightBluePalette[700],
  excellentIconActive: lightBluePalette[800],
  excellentIconDisabled: lightBluePalette["alpha40"],
  excellentIconInDefault: lightBluePalette[50],
  excellentIconInHover: lightBluePalette[100],
  excellentIconInActive: lightBluePalette[200],
  excellentIconInDisabled: lightBluePalette["alpha10"],

  // Neutral
  neutralBackgroundDefault: iocTealPalette[500],
  neutralBackgroundWeak: iocTealPalette.alpha10,
  neutralBackgroundDisabled: iocTealPalette.alpha40,
  neutralBackgroundHover: iocTealPalette[600],
  neutralBackgroundActive: iocTealPalette[700],
  neutralTextDefault: iocTealPalette[700],
  neutralTextHover: iocTealPalette[800],
  neutralTextActive: iocTealPalette[800],
  neutralTextInDefault: greyPalette[900],
  neutralTextInDisabled: iocTealPalette.alpha10,
  neutralBorderDefault: iocTealPalette[500],
  neutralBorderHover: iocTealPalette[600],
  neutralBorderActive: iocTealPalette[700],
  neutralBorderDisabled: iocTealPalette.alpha40,
  neutralBorderWeak: iocTealPalette.alpha20,
  neutralIconDefault: iocTealPalette[600],
  neutralIconHover: iocTealPalette[700],
  neutralIconActive: iocTealPalette[800],
  neutralIconDisabled: iocTealPalette.alpha40,
  neutralIconInDefault: iocTealPalette[50],
  neutralIconInHover: iocTealPalette[100],
  neutralIconInActive: iocTealPalette[200],
  neutralIconInDisabled: iocTealPalette.alpha10,

  // Info
  infoBackgroundDefault: iocBluePalette[500],
  infoBackgroundWeak: "rgba(43,130,246,0.10)",
  infoBackgroundDisabled: "rgba(43,130,246,0.40)",
  infoBackgroundHover: iocBluePalette[600],
  infoBackgroundActive: iocBluePalette[600],
  infoTextDefault: iocBluePalette[600],
  infoTextHover: "#1E6FD9",
  infoTextActive: "#1860C8",
  infoTextInDefault: greyPalette[900],
  infoTextInDisabled: "rgba(43,130,246,0.10)",
  infoBorderDefault: iocBluePalette[500],
  infoBorderHover: iocBluePalette[600],
  infoBorderActive: iocBluePalette[600],
  infoBorderDisabled: "rgba(43,130,246,0.40)",
  infoBorderWeak: "rgba(43,130,246,0.20)",
  infoIconDefault: iocBluePalette[500],
  infoIconHover: iocBluePalette[600],
  infoIconActive: iocBluePalette[600],
  infoIconDisabled: "rgba(43,130,246,0.40)",
  infoIconInDefault: "#EFF6FF",
  infoIconInHover: "#BFDBFE",
  infoIconInActive: "#93C5FD",
  infoIconInDisabled: "rgba(43,130,246,0.10)",

  // Inactive
  inactiveBackgroundDefault: greyPalette[300],
  inactiveBackgroundWeak: "rgba(60, 69, 81, 0.10)",
  inactiveBackgroundDisabled: greyPalette["alpha40"],
  inactiveBackgroundHover: greyPalette[400],
  inactiveBackgroundActive: greyPalette[500],
  inactiveTextDefault: greyPalette[600],
  inactiveTextHover: greyPalette[700],
  inactiveTextActive: greyPalette[700],
  inactiveTextInDefault: greyPalette[900],
  inactiveTextInDisabled: greyPalette["alpha40"],
  inactiveBorderDefault: greyPalette[300],
  inactiveBorderHover: greyPalette[400],
  inactiveBorderActive: greyPalette[500],
  inactiveBorderDisabled: greyPalette["alpha40"],
  inactiveBorderWeak: "rgba(60, 69, 81, 0.20)",
  inactiveIconDefault: greyPalette[400],
  inactiveIconHover: greyPalette[500],
  inactiveIconActive: greyPalette[600],
  inactiveIconDisabled: greyPalette["alpha40"],
  inactiveIconInDefault: greyPalette[0],
  inactiveIconInHover: greyPalette[50],
  inactiveIconInActive: greyPalette[100],
  inactiveIconInDisabled: greyPalette["alpha10"],

  // Warning
  warningBackgroundDefault: lightOrangePalette[500],
  warningBackgroundWeak: "rgba(251, 175, 69, 0.10)",
  warningBackgroundHover: lightOrangePalette[600],
  warningBackgroundActive: lightOrangePalette[700],
  warningBackgroundDisabled: lightOrangePalette["alpha40"],
  warningTextDefault: lightOrangePalette[700],
  warningTextHover: lightOrangePalette[800],
  warningTextActive: lightOrangePalette[800],
  warningTextInDefault: greyPalette[900],
  warningTextInDisabled: lightOrangePalette["alpha10"],
  warningBorderDefault: lightOrangePalette[500],
  warningBorderHover: lightOrangePalette[600],
  warningBorderActive: lightOrangePalette[700],
  warningBorderDisabled: lightOrangePalette["alpha40"],
  warningBorderWeak: "rgba(251, 175, 69, 0.30)",
  warningIconDefault: lightOrangePalette[500],
  warningIconHover: lightOrangePalette[600],
  warningIconActive: lightOrangePalette[700],
  warningIconDisabled: lightOrangePalette["alpha40"],
  warningIconInDefault: lightOrangePalette[50],
  warningIconInHover: lightOrangePalette[100],
  warningIconInActive: lightOrangePalette[200],
  warningIconInDisabled: lightOrangePalette["alpha10"],

  // Severe warning
  severeWarningBackgroundDefault: orangePalette[500],
  severeWarningBackgroundWeak: "rgba(242, 100, 61, 0.10)",
  severeWarningBackgroundHover: orangePalette[600],
  severeWarningBackgroundActive: orangePalette[700],
  severeWarningBackgroundDisabled: orangePalette["alpha40"],
  severeWarningTextDefault: orangePalette[700],
  severeWarningTextHover: orangePalette[800],
  severeWarningTextActive: orangePalette[800],
  severeWarningTextInDefault: greyPalette[900],
  severeWarningTextInDisabled: orangePalette["alpha10"],
  severeWarningBorderDefault: orangePalette[500],
  severeWarningBorderHover: orangePalette[600],
  severeWarningBorderActive: orangePalette[700],
  severeWarningBorderDisabled: orangePalette["alpha40"],
  severeWarningBorderWeak: "rgba(242, 100, 61, 0.30)",
  severeWarningIconDefault: orangePalette[500],
  severeWarningIconHover: orangePalette[600],
  severeWarningIconActive: orangePalette[700],
  severeWarningIconDisabled: orangePalette["alpha40"],
  severeWarningIconInDefault: orangePalette[50],
  severeWarningIconInHover: orangePalette[100],
  severeWarningIconInActive: orangePalette[200],
  severeWarningIconInDisabled: orangePalette["alpha10"],

  // Moderate
  moderateBackgroundDefault: yellowPalette[500],
  moderateBackgroundWeak: "rgba(255, 230, 89, 0.10)",
  moderateBackgroundHover: yellowPalette[600],
  moderateBackgroundActive: yellowPalette[700],
  moderateBackgroundDisabled: yellowPalette["alpha40"],
  moderateTextDefault: yellowPalette[900],
  moderateTextHover: yellowPalette[800],
  moderateTextActive: yellowPalette[800],
  moderateTextInDefault: greyPalette[900],
  moderateTextInDisabled: yellowPalette["alpha10"],
  moderateBorderDefault: yellowPalette[500],
  moderateBorderHover: yellowPalette[600],
  moderateBorderActive: yellowPalette[700],
  moderateBorderDisabled: yellowPalette["alpha40"],
  moderateBorderWeak: "rgba(255, 230, 89, 0.30)",
  moderateIconDefault: yellowPalette[700],
  moderateIconHover: yellowPalette[800],
  moderateIconActive: yellowPalette[800],
  moderateIconDisabled: yellowPalette["alpha40"],
  moderateIconInDefault: yellowPalette[900],
  moderateIconInHover: yellowPalette[800],
  moderateIconInActive: yellowPalette[700],
  moderateIconInDisabled: yellowPalette["alpha10"],

  // Accent colors (same palette, works on light too)
  accentADefault: lavenderPalette[600],
  accentAWeak: "rgba(140, 149, 255, 0.12)",
  accentBDefault: sunsetPalette[400],
  accentBWeak: "rgba(233, 106, 141, 0.12)",
  accentCDefault: sunsetPalette[200],
  accentCWeak: "rgba(243, 172, 162, 0.12)",
  accentDDefault: purplePalette[500],
  accentDWeak: "rgba(192, 128, 255, 0.12)",
  accentEDefault: limePalette[600],
  accentEWeak: "rgba(164, 197, 71, 0.12)",
  accentFDefault: orangePalette[500],
  accentFWeak: "rgba(244, 123, 90, 0.12)",
  accentGDefault: nightPalette[400],
  accentGWeak: "rgba(70, 170, 206, 0.12)",
  accentHDefault: iocTealPalette[600],
  accentHWeak: iocTealPalette.alpha10,
  accentIDefault: pinkPalette[500],
  accentIWeak: "rgba(242, 99, 140, 0.12)",
  accentJDefault: tealPalette[500],
  accentJWeak: "rgba(62, 203, 209, 0.12)",

  // Gradients
  // Shape — border radius
  borderRadiusSm: "4px",
  borderRadiusLg: "8px",
  borderRadius4xl: "20px",
  // Shape — border width
  borderWidthDefault: "1px",
  borderWidthStrong: "4px",
  gradientPrimary: `linear-gradient(180deg, ${iocTealPalette[400]} 0%, ${iocTealPalette[600]} 100%)`,
  gradientSecondary: `linear-gradient(180deg, ${iocBluePalette[500]} 0%, ${iocBluePalette[600]} 100%)`,
  gradientNegative: `linear-gradient(180deg, ${redPalette[400]} 0%, ${redPalette[500]} 100%)`,
  gradientBrand: `linear-gradient(135deg, ${iocTealPalette[400]} 0%, ${iocBluePalette[500]} 100%)`,
  gradientPage: iocLightPageBackground,

  // Glows — very subtle on light backgrounds
  glowPrimary: `0 0 4px ${iocTealPalette[500]}55, 0 0 10px ${iocTealPalette[500]}22`,
  glowSecondary: `0 0 4px ${iocBluePalette[500]}55, 0 0 10px ${iocBluePalette[500]}22`,
  glowSuccess: `0 0 4px ${greenPalette[500]}55, 0 0 10px ${greenPalette[500]}22`,
  glowWarning: `0 0 4px ${lightOrangePalette[500]}55, 0 0 10px ${lightOrangePalette[500]}22`,
  glowNegative: `0 0 4px ${redPalette[500]}55, 0 0 10px ${redPalette[500]}22`,
  glowSevere: `0 0 4px ${orangePalette[500]}55, 0 0 10px ${orangePalette[500]}22`,
  glowExcellent: `0 0 4px ${lightBluePalette[500]}55, 0 0 10px ${lightBluePalette[500]}22`,
  glowNeutral: `0 0 3px ${iocTealPalette[600]}44, 0 0 8px ${iocTealPalette[600]}18`,
};
