/*
 * Copyright 2025 Cisco Systems, Inc. and its affiliates
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { VarsType } from "@/types/vars";
import {
  greenPalette,
  greyPalette,
  lightOrangePalette,
  redPalette,
  lightBluePalette,
  purplePalette,
  orangePalette,
  yellowPalette,
  nightPalette,
  sunsetPalette,
  lavenderPalette,
  limePalette,
  pinkPalette,
  tealPalette,
} from "../color-palette";
import {
  iocTealPalette,
  iocBluePalette,
  iocSurfacePalette,
  iocBackdropPalette,
  iocBorderPalette,
  iocTextPrimary,
  iocTextSecondary,
  iocTextTertiary,
  iocTextDisabled,
} from "./ioc-color-palette";

export const iocVars: VarsType = {
  // Brand
  brandOrange: lightOrangePalette[500],
  brandOrangeDark: lightOrangePalette[900],
  brandBlue: iocTealPalette[500],
  brandMidnightBlue: iocBackdropPalette[500],
  agentcyYellow: lightOrangePalette[500],
  agentcyBlue: iocTealPalette[500],
  agentcyDarkBlue: iocBackdropPalette[900],

  // Text
  baseTextStrong: iocTextPrimary,
  baseTextDefault: iocTextSecondary,
  baseTextMedium: iocTextTertiary,
  baseTextWeak: iocTextDisabled,
  baseTextInverse: iocBackdropPalette[900],
  baseTextDisabled: iocTextDisabled,

  // Background
  baseBackgroundStrong: iocBackdropPalette[900],
  baseBackgroundMedium: iocSurfacePalette[200],
  baseBackgroundWeak: iocSurfacePalette[100],
  baseBackgroundHover: iocSurfacePalette[300],

  // Border
  baseBorderDefault: iocBorderPalette[300],
  baseBorderStrong: iocBorderPalette[500],
  baseBorderMedium: iocBorderPalette[200],
  baseBorderWeak: iocBorderPalette[100],

  // Brand icon
  brandIconPrimaryDefault: iocTealPalette[500],
  brandIconPrimaryWeak: iocTealPalette[200],
  brandIconPrimaryMedium: iocTealPalette[400],
  brandIconPrimaryStrong: iocTealPalette[700],
  brandIconSecondaryDefault: iocBluePalette[500],
  brandIconSecondaryWeak: iocBluePalette[400],
  brandIconSecondaryMedium: iocBluePalette[500],
  brandIconTertiaryDefault: lightOrangePalette[500],
  brandIconTertiaryWeak: lightOrangePalette[200],
  brandIconTertiaryMedium: lightOrangePalette[400],

  // Brand background
  brandBackgroundPrimaryDefault: iocTealPalette[500],
  brandBackgroundPrimaryWeak: iocTealPalette.alpha10,
  brandBackgroundPrimaryMedium: iocTealPalette.alpha20,
  brandBackgroundSecondaryDefault: iocBluePalette[500],
  brandLogoPrimary: iocTealPalette[400],
  brandTextPrimary: iocTealPalette[400],
  brandTextSecondary: iocTextPrimary,

  // Control
  controlBackgroundDefault: iocSurfacePalette[100],
  controlBackgroundDisabled: iocSurfacePalette[50],
  controlBackgroundWeak: iocSurfacePalette[50],
  controlBackgroundMedium: iocSurfacePalette[300],
  controlBorderDefault: iocBorderPalette[300],
  controlBorderStrong: iocBorderPalette[500],
  controlBorderMedium: iocBorderPalette[200],
  controlBorderWeak: iocBorderPalette[100],
  controlBorderHover: iocTealPalette[500],
  controlBorderActive: iocTealPalette[600],
  controlBorderNegative: redPalette[500],
  controlBorderDisabled: iocBorderPalette[100],
  controlIconDefault: iocTextSecondary,
  controlIconStrong: iocTextPrimary,
  controlIconMedium: iocTextTertiary,
  controlIconWeak: iocTextDisabled,
  controlIconHover: iocTealPalette[400],
  controlIconActive: iocTealPalette[500],
  controlIconDisabled: iocTextDisabled,

  // Interactive primary (teal)
  interactivePrimaryDefaultDefault: iocTealPalette[500],
  interactivePrimaryDefaultHover: iocTealPalette[400],
  interactivePrimaryDefaultActive: iocTealPalette[600],
  interactivePrimaryDefaultDisabled: iocTealPalette.alpha40,
  interactivePrimaryWeakDefault: iocTealPalette.alpha10,
  interactivePrimaryWeakHover: iocTealPalette.alpha20,
  interactivePrimaryWeakActive: iocTealPalette.alpha40,
  interactivePrimaryWeakDisabled: iocTealPalette.alpha05,

  // Interactive secondary (blue)
  interactiveSecondaryDefaultDefault: iocBluePalette[500],
  interactiveSecondaryDefaultHover: iocBluePalette[400],
  interactiveSecondaryDefaultActive: iocBluePalette[600],
  interactiveSecondaryDefaultDisabled: "rgba(43,130,246,0.40)",
  interactiveSecondaryWeakDefault: iocSurfacePalette[200],
  interactiveSecondaryWeakHover: iocSurfacePalette[300],
  interactiveSecondaryWeakActive: iocSurfacePalette[400],
  interactiveSecondaryWeakDisabled: iocSurfacePalette[100],

  // Interactive inverse
  interactiveInverseBackgroundDefault: "rgba(255,255,255,0.90)",
  interactiveInverseBackgroundHover: "rgba(255,255,255,0.95)",
  interactiveInverseBackgroundActive: "rgba(255,255,255,0.85)",
  interactiveInverseBackgroundDisabled: "rgba(255,255,255,0.40)",
  interactiveInverseTextDefault: iocBackdropPalette[900],
  interactiveInverseTextHover: iocBackdropPalette[700],
  interactiveInverseTextActive: iocBackdropPalette[800],
  interactiveInverseTextDisabled: "rgba(0,0,0,0.30)",

  // Interactive text in
  interactiveTextInDefault: iocTextPrimary,
  interactiveTextInHover: iocTextPrimary,
  interactiveTextInActive: iocTextPrimary,
  interactiveTextInDisabled: iocTextDisabled,

  // Interactive tertiary
  interactiveTertiaryDefault: lightOrangePalette[500],
  interactiveTertiaryHover: lightOrangePalette[400],
  interactiveTertiaryActive: lightOrangePalette[600],
  interactiveTertiaryDisabled: lightOrangePalette["alpha40"],

  // Success
  successBackgroundDefault: greenPalette[500],
  successBackgroundDisabled: greenPalette[40],
  successBackgroundHover: greenPalette[400],
  successBackgroundActive: greenPalette[600],
  successBackgroundWeak: "rgba(0, 185, 141, 0.10)",
  successIconActive: greenPalette[600],
  successIconDisabled: greenPalette[40],
  successIconHover: greenPalette[400],
  successIconDefault: greenPalette[500],
  successTextActive: greenPalette[300],
  successTextHover: greenPalette[200],
  successTextDefault: greenPalette[300],
  successTextInDisabled: greenPalette[10],
  successTextInDefault: greenPalette[50],
  successBorderDisabled: greenPalette[40],
  successBorderActive: greenPalette[600],
  successBorderHover: greenPalette[400],
  successBorderDefault: greenPalette[500],
  successBorderWeak: "rgba(0, 185, 141, 0.30)",
  successIconInDisabled: greenPalette[10],
  successIconInActive: greenPalette[200],
  successIconInHover: greenPalette[100],
  successIconInDefault: greenPalette[50],

  // Negative
  negativeBackgroundHover: redPalette[400],
  negativeBackgroundActive: redPalette[600],
  negativeBackgroundDisabled: redPalette["alpha40"],
  negativeBackgroundDefault: redPalette[500],
  negativeBackgroundWeak: "rgba(198, 41, 83, 0.10)",
  negativeTextDefault: redPalette[300],
  negativeTextHover: redPalette[200],
  negativeTextActive: redPalette[400],
  negativeBorderActive: redPalette[600],
  negativeBorderHover: redPalette[400],
  negativeBorderDisabled: redPalette["alpha40"],
  negativeBorderDefault: redPalette[500],
  negativeBorderWeak: "rgba(198, 41, 83, 0.30)",
  negativeIconDisabled: redPalette["alpha40"],
  negativeIconActive: redPalette[600],
  negativeIconHover: redPalette[400],
  negativeIconDefault: redPalette[500],
  negativeTextInDefault: redPalette[50],
  negativeTextInDisabled: redPalette["alpha10"],
  negativeIconInDefault: redPalette[50],
  negativeIconInHover: redPalette[100],
  negativeIconInActive: redPalette[200],
  negativeIconInDisabled: redPalette["alpha10"],

  // Excellent
  excellentBackgroundDefault: lightBluePalette[600],
  excellentBackgroundWeak: "rgba(31, 210, 255, 0.10)",
  excellentBackgroundDisabled: lightBluePalette["alpha40"],
  excellentBackgroundHover: lightBluePalette[500],
  excellentBackgroundActive: lightBluePalette[700],
  excellentTextDefault: lightBluePalette[200],
  excellentTextHover: lightBluePalette[100],
  excellentTextActive: lightBluePalette[300],
  excellentTextInDefault: lightBluePalette[50],
  excellentTextInDisabled: lightBluePalette["alpha10"],
  excellentBorderDefault: lightBluePalette[600],
  excellentBorderHover: lightBluePalette[500],
  excellentBorderActive: lightBluePalette[700],
  excellentBorderDisabled: lightBluePalette["alpha40"],
  excellentBorderWeak: "rgba(31, 210, 255, 0.30)",
  excellentIconDefault: lightBluePalette[500],
  excellentIconHover: lightBluePalette[400],
  excellentIconActive: lightBluePalette[600],
  excellentIconDisabled: lightBluePalette["alpha40"],
  excellentIconInDefault: lightBluePalette[50],
  excellentIconInHover: lightBluePalette[100],
  excellentIconInActive: lightBluePalette[200],
  excellentIconInDisabled: lightBluePalette["alpha10"],

  // Neutral
  neutralBackgroundDefault: iocTealPalette[600],
  neutralBackgroundWeak: iocTealPalette.alpha10,
  neutralBackgroundDisabled: iocTealPalette.alpha40,
  neutralBackgroundHover: iocTealPalette[500],
  neutralBackgroundActive: iocTealPalette[700],
  neutralTextDefault: iocTealPalette[200],
  neutralTextHover: iocTealPalette[100],
  neutralTextActive: iocTealPalette[300],
  neutralTextInDefault: iocTealPalette[50],
  neutralTextInDisabled: iocTealPalette.alpha10,
  neutralBorderDefault: iocTealPalette[600],
  neutralBorderHover: iocTealPalette[500],
  neutralBorderActive: iocTealPalette[700],
  neutralBorderDisabled: iocTealPalette.alpha40,
  neutralBorderWeak: iocTealPalette.alpha20,
  neutralIconDefault: iocTealPalette[500],
  neutralIconHover: iocTealPalette[400],
  neutralIconActive: iocTealPalette[600],
  neutralIconDisabled: iocTealPalette.alpha40,
  neutralIconInDefault: iocTealPalette[50],
  neutralIconInHover: iocTealPalette[100],
  neutralIconInActive: iocTealPalette[200],
  neutralIconInDisabled: iocTealPalette.alpha10,

  // Info
  infoBackgroundDefault: iocBluePalette[600],
  infoBackgroundWeak: "rgba(43,130,246,0.10)",
  infoBackgroundDisabled: "rgba(43,130,246,0.40)",
  infoBackgroundHover: iocBluePalette[500],
  infoBackgroundActive: iocBluePalette[600],
  infoTextDefault: "#93C5FD",
  infoTextHover: "#BFDBFE",
  infoTextActive: "#60A5FA",
  infoTextInDefault: "#EFF6FF",
  infoTextInDisabled: "rgba(43,130,246,0.10)",
  infoBorderDefault: iocBluePalette[600],
  infoBorderHover: iocBluePalette[500],
  infoBorderActive: iocBluePalette[600],
  infoBorderDisabled: "rgba(43,130,246,0.40)",
  infoBorderWeak: "rgba(43,130,246,0.20)",
  infoIconDefault: iocBluePalette[500],
  infoIconHover: iocBluePalette[400],
  infoIconActive: iocBluePalette[600],
  infoIconDisabled: "rgba(43,130,246,0.40)",
  infoIconInDefault: "#EFF6FF",
  infoIconInHover: "#BFDBFE",
  infoIconInActive: "#93C5FD",
  infoIconInDisabled: "rgba(43,130,246,0.10)",

  // Inactive
  inactiveBackgroundDefault: greyPalette[600],
  inactiveBackgroundWeak: "rgba(60, 69, 81, 0.10)",
  inactiveBackgroundDisabled: greyPalette["alpha40"],
  inactiveBackgroundHover: greyPalette[500],
  inactiveBackgroundActive: greyPalette[700],
  inactiveTextDefault: greyPalette[200],
  inactiveTextHover: greyPalette[100],
  inactiveTextActive: greyPalette[300],
  inactiveTextInDefault: greyPalette[50],
  inactiveTextInDisabled: greyPalette["alpha40"],
  inactiveBorderDefault: greyPalette[600],
  inactiveBorderHover: greyPalette[500],
  inactiveBorderActive: greyPalette[700],
  inactiveBorderDisabled: greyPalette["alpha40"],
  inactiveBorderWeak: "rgba(60, 69, 81, 0.30)",
  inactiveIconDefault: greyPalette[400],
  inactiveIconHover: greyPalette[300],
  inactiveIconActive: greyPalette[500],
  inactiveIconDisabled: greyPalette["alpha40"],
  inactiveIconInDefault: greyPalette[0],
  inactiveIconInHover: greyPalette[50],
  inactiveIconInActive: greyPalette[100],
  inactiveIconInDisabled: greyPalette["alpha10"],

  // Warning
  warningBackgroundDefault: lightOrangePalette[500],
  warningBackgroundWeak: "rgba(251, 175, 69, 0.10)",
  warningBackgroundHover: lightOrangePalette[400],
  warningBackgroundActive: lightOrangePalette[600],
  warningBackgroundDisabled: lightOrangePalette["alpha40"],
  warningTextDefault: lightOrangePalette[200],
  warningTextHover: lightOrangePalette[100],
  warningTextActive: lightOrangePalette[300],
  warningTextInDefault: lightOrangePalette[50],
  warningTextInDisabled: lightOrangePalette["alpha10"],
  warningBorderDefault: lightOrangePalette[500],
  warningBorderHover: lightOrangePalette[400],
  warningBorderActive: lightOrangePalette[600],
  warningBorderDisabled: lightOrangePalette["alpha40"],
  warningBorderWeak: "rgba(251, 175, 69, 0.30)",
  warningIconDefault: lightOrangePalette[500],
  warningIconHover: lightOrangePalette[400],
  warningIconActive: lightOrangePalette[600],
  warningIconDisabled: lightOrangePalette["alpha40"],
  warningIconInDefault: lightOrangePalette[50],
  warningIconInHover: lightOrangePalette[100],
  warningIconInActive: lightOrangePalette[200],
  warningIconInDisabled: lightOrangePalette["alpha10"],

  // Severe warning
  severeWarningBackgroundDefault: orangePalette[500],
  severeWarningBackgroundWeak: "rgba(242, 100, 61, 0.10)",
  severeWarningBackgroundHover: orangePalette[400],
  severeWarningBackgroundActive: orangePalette[600],
  severeWarningBackgroundDisabled: orangePalette["alpha40"],
  severeWarningTextDefault: orangePalette[200],
  severeWarningTextHover: orangePalette[100],
  severeWarningTextActive: orangePalette[300],
  severeWarningTextInDefault: orangePalette[50],
  severeWarningTextInDisabled: orangePalette["alpha10"],
  severeWarningBorderDefault: orangePalette[500],
  severeWarningBorderHover: orangePalette[400],
  severeWarningBorderActive: orangePalette[600],
  severeWarningBorderDisabled: orangePalette["alpha40"],
  severeWarningBorderWeak: "rgba(242, 100, 61, 0.30)",
  severeWarningIconDefault: orangePalette[500],
  severeWarningIconHover: orangePalette[400],
  severeWarningIconActive: orangePalette[600],
  severeWarningIconDisabled: orangePalette["alpha40"],
  severeWarningIconInDefault: orangePalette[50],
  severeWarningIconInHover: orangePalette[100],
  severeWarningIconInActive: orangePalette[200],
  severeWarningIconInDisabled: orangePalette["alpha10"],

  // Moderate
  moderateBackgroundDefault: yellowPalette[500],
  moderateBackgroundWeak: "rgba(255, 230, 89, 0.10)",
  moderateBackgroundHover: yellowPalette[400],
  moderateBackgroundActive: yellowPalette[600],
  moderateBackgroundDisabled: yellowPalette["alpha40"],
  moderateTextDefault: yellowPalette[900],
  moderateTextHover: yellowPalette[800],
  moderateTextActive: yellowPalette[700],
  moderateTextInDefault: yellowPalette[900],
  moderateTextInDisabled: yellowPalette["alpha10"],
  moderateBorderDefault: yellowPalette[500],
  moderateBorderHover: yellowPalette[400],
  moderateBorderActive: yellowPalette[600],
  moderateBorderDisabled: yellowPalette["alpha40"],
  moderateBorderWeak: "rgba(255, 230, 89, 0.30)",
  moderateIconDefault: yellowPalette[700],
  moderateIconHover: yellowPalette[600],
  moderateIconActive: yellowPalette[800],
  moderateIconDisabled: yellowPalette["alpha40"],
  moderateIconInDefault: yellowPalette[900],
  moderateIconInHover: yellowPalette[800],
  moderateIconInActive: yellowPalette[700],
  moderateIconInDisabled: yellowPalette["alpha10"],

  // Accent colors
  accentADefault: lavenderPalette[400],
  accentAWeak: "rgba(140, 149, 255, 0.15)",
  accentBDefault: sunsetPalette[300],
  accentBWeak: "rgba(233, 106, 141, 0.15)",
  accentCDefault: sunsetPalette[100],
  accentCWeak: "rgba(243, 172, 162, 0.15)",
  accentDDefault: purplePalette[400],
  accentDWeak: "rgba(192, 128, 255, 0.15)",
  accentEDefault: limePalette[400],
  accentEWeak: "rgba(164, 197, 71, 0.15)",
  accentFDefault: orangePalette[400],
  accentFWeak: "rgba(244, 123, 90, 0.15)",
  accentGDefault: nightPalette[200],
  accentGWeak: "rgba(70, 170, 206, 0.15)",
  accentHDefault: iocTealPalette[400],
  accentHWeak: iocTealPalette.alpha10,
  accentIDefault: pinkPalette[400],
  accentIWeak: "rgba(242, 99, 140, 0.15)",
  accentJDefault: tealPalette[400],
  accentJWeak: "rgba(62, 203, 209, 0.15)",
};
